import { previewPublications } from "./helpers/publication-preview.js";
import { drawnSignature } from "./helpers/signatures.js";
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { startLocalPostgres } from './helpers/local-postgres.js';
import { installAgreementSystem } from '../quote-agreements.js';
import { installAgreementPayments } from '../agreement-payments.js';
import { installAgreementPlans } from '../agreement-plans.js';
import { installAgreementArchive } from '../agreement-archive.js';
import { installAgreementPlanBilling } from '../agreement-plan-billing.js';
import { advancePlanDate } from '../agreement-plans-domain.js';

test('tier offers, separate consent, conditional adjustments and existing memberships remain atomic', {timeout:120000}, async (t) => {
  const postgres=startLocalPostgres();postgres.configureEnvironment();let server,pool;
  try {
    const backend=await import('../index.js');pool=backend.pool;await backend.bootstrap();
    const env={NODE_ENV:'test',STRIPE_MODE:'test',QUOTE_PUBLIC_BASE_URL:'http://localhost:3000',QUOTE_LINK_SECRET:'test-only-long-cryptographic-link-key-never-production'};
    const service=await installAgreementSystem({app:backend.app,pool,authRequired:backend.authRequired,requireCapability:backend.requireCapability,getQuoteSettings:backend.getQuoteSettings,env,startWorker:false});
    previewPublications(service);
    await installAgreementPayments({app:backend.app,pool,service,env,getStripe:()=>null,authRequired:backend.authRequired,requireCapability:backend.requireCapability,startWorker:false});
    const plans=await installAgreementPlans({app:backend.app,pool,service,authRequired:backend.authRequired,requireCapability:backend.requireCapability,startWorker:false});
    const company=randomUUID(),otherCompany=randomUUID(),owner=randomUUID(),otherOwner=randomUUID(),contact=randomUUID(),quote=randomUUID(),windowID=randomUUID(),pressureID=randomUUID();
    await pool.query("INSERT INTO companies(id,name,join_code) VALUES($1,'Plans Test','PLAN-TEST'),($2,'Other Plans','PLAN-OTHER')",[company,otherCompany]);
    await pool.query("INSERT INTO users(id,email,role,company_id) VALUES($1,'planowner@example.invalid','employer',$3),($2,'planother@example.invalid','employer',$4)",[owner,otherOwner,company,otherCompany]);
    await pool.query('UPDATE companies SET owner_user_id=$2 WHERE id=$1',[company,owner]);
    await pool.query("INSERT INTO sessions(token,user_id) VALUES('plan-owner',$1),('plan-other',$2)",[owner,otherOwner]);
    await pool.query("INSERT INTO contacts(id,user_id,company_id,name,email,address) VALUES($1,$2,$3,'Plan Customer','plans@example.invalid','123 Plan Lane')",[contact,owner,company]);
    await pool.query("INSERT INTO saved_services(id,company_id,name,default_price_cents,plan_eligible) VALUES($1,$3,'Windows',30000,true),($2,$3,'Pressure',40000,false)",[windowID,pressureID,company]);
    const lines=[{id:randomUUID(),service_id:windowID,name:'Windows',qty:1,price_cents:30000},{id:randomUUID(),service_id:pressureID,name:'Pressure',qty:1,price_cents:40000}];
    await pool.query("INSERT INTO quotes(id,user_id,company_id,contact_id,title,line_items,total_cents,quote_options) VALUES($1,$2,$3,$4,'Initial job',$5::jsonb,70000,$6::jsonb)",[quote,owner,company,contact,JSON.stringify(lines),JSON.stringify({duration_minutes:60,offer_service_plans:true})]);
    await pool.query("INSERT INTO agreement_settings(company_id,content) VALUES($1,$2::jsonb)",[company,JSON.stringify({consent_text:'I agree to this initial job.'})]);
    server=await new Promise(resolve=>{const listener=backend.app.listen(0,'127.0.0.1',()=>resolve(listener));});const base=`http://127.0.0.1:${server.address().port}`;
    const request=async(path,{method='GET',body,token='plan-owner'}={})=>{const response=await fetch(base+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});return{status:response.status,body:await response.json()};};
    const config={name:'Quarterly windows',discount:{type:'percent',value:1500},discount_first_visit:true,allow_skip:true,service_interval:{unit:'month',count:3},billing:{mode:'manual_per_visit'},term:{kind:'finite',visit_count:4},cancellation_policy:'Cancel future unperformed services with30 days notice. No automatic renewal.',agreement:{agreement_text:'Window plan for {{customer_name}}. {{billing_information}}',consent_text:'I separately agree to this service plan.'}};
    let tier,published,token,offer,enrollment;
    const sign=async(agreement)=>{const link=agreement.customer_url.split('/').at(-1);const session=(await request(`/api/public/agreements/${link}/session`,{method:'POST',token:null,body:{}})).body;const result=await request(`/api/public/agreements/${link}/sign`,{method:'POST',token:null,body:{request_id:randomUUID(),session_token:session.session_token,packet_hash:agreement.packet_hash,printed_name:'Plan Customer',consent:true,signature:drawnSignature(),values:{}}});assert.equal(result.status,200,JSON.stringify(result.body));return result;};
    await t.test('tenant-owned tiers and eligibility use stable catalog references and version checks',async()=>{
      const saved=await request('/api/service-plan-tiers',{method:'POST',body:{configuration:config}});assert.equal(saved.status,201,JSON.stringify(saved.body));tier=saved.body;
      assert.equal((await request('/api/service-plan-tiers',{token:'plan-other'})).body.tiers.length,0);
      assert.equal((await request('/api/service-plan-tiers',{method:'POST',token:'plan-other',body:{tier_id:tier.tier_id,expected_version:1,configuration:config}})).status,409);
      assert.equal((await request('/api/service-plan-tiers',{method:'POST',body:{tier_id:tier.tier_id,expected_version:0,configuration:config}})).status,409);
      published=(await request(`/api/quotes/${quote}/publish`,{method:'POST',body:{request_id:randomUUID()}})).body;assert.ok(published.id,JSON.stringify(published));token=published.customer_url.split('/').at(-1);
      assert.equal((await request(`/api/public/agreements/${token}/plan-offers`,{token:null})).body.offers.length,0);
      await sign(published);
      await pool.query("INSERT INTO payment_records(user_id,company_id,contact_id,quote_id,payment_type,status,amount_cents,currency) VALUES($1,$2,$3,$4,'manual','succeeded',15000,'usd')",[owner,company,contact,quote]);
      const result=await request(`/api/public/agreements/${token}/plan-offers`,{token:null});assert.equal(result.status,200,JSON.stringify(result.body));offer=result.body.offers[0];
      assert.equal(offer.current_total_cents,65500);assert.equal(offer.current_balance_cents,50500);assert.equal(offer.future_visit.total_cents,25500);assert.deepEqual(offer.eligible_line_ids,[lines[0].id]);
    });
    await t.test('plan-specific quote freezes its tier, discounts once, signs and activates the actual membership',async()=>{
      const planQuote=randomUUID();
      await pool.query("INSERT INTO quotes(id,user_id,company_id,contact_id,title,line_items,total_cents,quote_options) VALUES($1,$2,$3,$4,'Direct plan',$5::jsonb,70000,$6::jsonb)",[planQuote,owner,company,contact,JSON.stringify(lines),JSON.stringify({duration_minutes:60})]);
      const draft={request_id:randomUUID(),content:{plan_tier_id:tier.tier_id}};
      const result=await request(`/api/quotes/${planQuote}/publish`,{method:'POST',body:draft});assert.equal(result.status,201,JSON.stringify(result.body));
      let direct=result.body;
      const revised=await request(`/api/quotes/${planQuote}/publish`,{method:'POST',body:{...draft,request_id:randomUUID()}});
      assert.equal(revised.status,201,JSON.stringify(revised.body));assert.equal(revised.body.customer_url,direct.customer_url);
      assert.equal(revised.body.revision,2);assert.equal((await pool.query('SELECT state FROM agreement_plan_enrollments WHERE id=$1',[direct.plan.id])).rows[0].state,'canceled');
      assert.equal((await pool.query('SELECT count(*)::int AS count FROM agreement_plan_enrollments WHERE collection_key=$1 AND canceled_at IS NULL',[`quote:${planQuote}`])).rows[0].count,1);
      direct=revised.body; assert.equal(direct.snapshot.pricing.total_cents,65500);assert.equal(direct.snapshot.offer_service_plans,false);assert.equal(direct.snapshot.plan_quote.tier_version,1);
      assert.equal(direct.snapshot.pricing.line_items.reduce((sum,line)=>sum+line.total_cents,0),65500);
      assert.equal(direct.plan.service_plan_id,null);assert.equal(direct.plan.plan_agreement_id,direct.id);
      await sign(direct);
      const blockedRevision=await request(`/api/quotes/${planQuote}/publish`,{method:'POST',body:{request_id:randomUUID(),content:{plan_tier_id:null}}});
      assert.equal(blockedRevision.status,409);assert.equal(blockedRevision.body.error,'plan_quote_already_issued');
      const link=direct.customer_url.split('/').at(-1);
      const ready=await request(`/api/public/agreements/${link}/enrollments/${direct.plan.id}/reconcile`,{method:'POST',token:null,body:{}});assert.equal(ready.status,200,JSON.stringify(ready.body));assert.ok(ready.body.service_plan_id);
      const after=(await request(`/api/agreements/${direct.id}`)).body;assert.equal(after.payments.total_cents,65500);assert.equal(after.payments.adjustment_cents,0);
      assert.equal(after.plan.snapshot.configuration.name,config.name);
      // Preserve this fixture while keeping legacy count assertions below local to the original enrollment.
      await pool.query("UPDATE service_plans SET status='canceled' WHERE id=$1",[ready.body.service_plan_id]);
      await pool.query("UPDATE agreement_plan_enrollments SET canceled_at=now(),state='canceled' WHERE id=$1",[direct.plan.id]);
    });
    await t.test('employee removal commits, revokes login and keeps historical identity out of active rosters',async()=>{
      const worker=randomUUID(),email='former-worker@example.invalid';
      await pool.query("INSERT INTO users(id,email,role,company_id,display_name,password_hash) VALUES($1,$2,'employee',$3,'Former worker','fixture')",[worker,email,company]);
      await pool.query("INSERT INTO sessions(token,user_id) VALUES('former-worker-session',$1)",[worker]);
      await pool.query("INSERT INTO magic_tokens(email,code,expires_at) VALUES($1,'fixture',now()+interval '1 hour')",[email]);
      const result=await request(`/api/company/employees/${worker}`,{method:'DELETE'});assert.equal(result.status,200,JSON.stringify(result.body));
      const saved=(await pool.query('SELECT * FROM users WHERE id=$1',[worker])).rows[0];assert.ok(saved.deleted_at);assert.equal(saved.display_name,'Former worker');assert.equal(saved.password_hash,null);
      assert.equal((await pool.query('SELECT 1 FROM sessions WHERE user_id=$1',[worker])).rowCount,0);assert.equal((await pool.query('SELECT 1 FROM magic_tokens WHERE email=$1',[email])).rowCount,0);
      assert.equal((await request('/api/company/users',{token:'former-worker-session'})).status,401);
      assert.ok(!(await request('/api/company/users')).body.some(user=>user.id===worker));
    });
    await t.test('concurrent selection creates one pending enrollment and no discount before separate signing',async()=>{
      const body={request_id:randomUUID(),tier_id:tier.tier_id,tier_version:tier.version,offer_hash:offer.offer_hash};
      const results=await Promise.all([1,2,3].map(()=>request(`/api/public/agreements/${token}/enrollments`,{method:'POST',token:null,body})));
      assert.ok(results.every(result=>result.status===201),JSON.stringify(results));enrollment=results[0].body;assert.ok(results.every(result=>result.body.id===enrollment.id));
      assert.equal(enrollment.state,'agreement_pending');assert.equal(enrollment.service_plan_id,null);
      assert.equal((await request(`/api/agreements/${published.id}`)).body.payments.balance_cents,55000);
      const reconciled=await request(`/api/public/agreements/${token}/enrollments/${enrollment.id}/reconcile`,{method:'POST',token:null,body:{}});assert.equal(reconciled.body.state,'agreement_pending');
      assert.equal((await pool.query("SELECT count(*)::integer n FROM service_plans WHERE status='active'")).rows[0].n,0);
      const planAgreement=(await request(`/api/agreements/${enrollment.plan_agreement_id}`)).body;
      assert.match(planAgreement.snapshot.agreement_text,/initial job.*original \$700.00/i);assert.equal(planAgreement.snapshot.kind,'plan');
      await sign(planAgreement);
      await pool.query('UPDATE saved_services SET plan_eligible=false,name=\'Renamed archived window\',archived_at=now() WHERE id=$1',[windowID]);
      // An already signed enrollment retains the offered scope when defaults change.
      const activations=await Promise.all([1,2,3].map(()=>request(`/api/public/agreements/${token}/enrollments/${enrollment.id}/reconcile`,{method:'POST',token:null,body:{}})));
      assert.ok(activations.every(result=>result.status===200),JSON.stringify(activations));assert.ok(activations.every(result=>result.body.state==='active'),JSON.stringify(activations));
      assert.equal((await pool.query("SELECT count(*)::integer n FROM service_plans WHERE status='active'")).rows[0].n,1);
      assert.equal((await pool.query('SELECT count(*)::integer n FROM agreement_quote_adjustments')).rows[0].n,1);
      const after=(await request(`/api/agreements/${published.id}`)).body;assert.equal(after.snapshot.pricing.total_cents,70000);assert.equal(after.payments.total_cents,65500);assert.equal(after.payments.paid_cents,15000);assert.equal(after.payments.balance_cents,50500);assert.ok(after.plan.service_plan_id);
      const membership=(await request(`/api/service-plans/${after.plan.service_plan_id}`)).body;assert.ok(membership.id,JSON.stringify(membership));assert.equal(membership.price_cents,25500);
      assert.equal((await pool.query('SELECT count(*)::integer n FROM agreement_plan_visits WHERE enrollment_id=$1',[enrollment.id])).rows[0].n,4);
    });
    await t.test('operations show one next visit, hide a scheduled membership, and dashboard uses service cadence',async()=>{
      const current=(await request(`/api/agreements/${published.id}`)).body.plan;
      const operations=await request('/api/service-plan-operations');assert.equal(operations.status,200,JSON.stringify(operations.body));assert.equal(operations.body.unscheduled.length,1);assert.equal(operations.body.unscheduled[0].service_plan_id,current.service_plan_id);
      const dashboard=await request('/api/service-plans/dashboard');assert.equal(dashboard.body.active_count,1);assert.equal(dashboard.body.estimated_mrr_cents,8500);
      assert.equal((await request('/api/service-plan-operations',{token:'plan-other'})).body.unscheduled.length,0);
    });
    await t.test('actual linked completed jobs consume one entitlement and preserve next obligation',async()=>{
      const current=(await request(`/api/agreements/${published.id}`)).body.plan;
      const visit=current.visits[0],jobID=randomUUID();
      await pool.query("INSERT INTO schedule_events(id,user_id,company_id,title,start_at,end_at,contact_id,service_items) VALUES($1,$2,$3,'Future windows',now()+interval '90 days',now()+interval '90 days 1 hour',$4,$5::jsonb)",[jobID,owner,company,contact,JSON.stringify([lines[0]])]);
      const path=`/api/service-plan-enrollments/${current.id}/visits/${visit.id}/schedule`;
      assert.equal((await request(path,{method:'POST',token:'plan-other',body:{job_id:jobID}})).status,404);
      const linked=await request(path,{method:'POST',body:{job_id:jobID}});assert.equal(linked.status,200,JSON.stringify(linked.body));
      assert.equal(linked.body.visits[0].state,'scheduled');
      assert.equal((await request('/api/service-plan-operations')).body.unscheduled.length,0);
      const membership=(await pool.query('SELECT * FROM service_plans WHERE id=$1',[current.service_plan_id])).rows[0];
      const body={request_id:randomUUID(),job_id:jobID};
      await assert.rejects(plans.markServiced({companyId:company,userId:owner},membership,body),/finish that job/);
      await pool.query('UPDATE schedule_events SET finished_at=now(),finished_by=$2 WHERE id=$1',[jobID,owner]);
      await Promise.all([1,2,3].map(()=>plans.markServiced({companyId:company,userId:owner},membership,body)));
      const after=(await pool.query('SELECT * FROM service_plans WHERE id=$1',[membership.id])).rows[0];
      assert.equal(after.remaining_visits,3);assert.ok(after.next_service_date);
      assert.equal((await request('/api/service-plan-operations')).body.unscheduled.length,1);
      assert.equal((await pool.query("SELECT count(*)::integer n FROM service_plan_events WHERE service_plan_id=$1 AND event_type='serviced'",[membership.id])).rows[0].n,1);
      assert.equal((await pool.query("SELECT count(*)::integer n FROM agreement_plan_visits WHERE enrollment_id=$1 AND state='completed'",[current.id])).rows[0].n,1);
      assert.equal((await request(path,{method:'POST',body:{job_id:jobID}})).status,409);
    });
    await t.test('linked job scope is guarded and canceled appointments restore deferable entitlement without billing changes',async()=>{
      const current=(await request(`/api/agreements/${published.id}`)).body.plan,visit=current.visits.find(visit=>visit.state==='due'),jobID=randomUUID();
      await pool.query("INSERT INTO schedule_events(id,user_id,company_id,title,start_at,end_at,contact_id,service_items) VALUES($1,$2,$3,'Future windows',now()+interval '180 days',now()+interval '180 days 1 hour',$4,$5::jsonb)",[jobID,owner,company,contact,JSON.stringify([lines[0]])]);
      assert.equal((await request(`/api/service-plan-enrollments/${current.id}/visits/${visit.id}/schedule`,{method:'POST',body:{job_id:jobID}})).status,200);
      await assert.rejects(pool.query("UPDATE schedule_events SET service_items='[]'::jsonb WHERE id=$1",[jobID]),/signed_plan_job_scope_immutable/);
      await assert.rejects(pool.query('UPDATE schedule_events SET service_plan_id=NULL WHERE id=$1',[jobID]),/signed_plan_job_scope_immutable/);
      await pool.query("UPDATE schedule_events SET title='Operational title updated' WHERE id=$1",[jobID]);
      const path=`/api/service-plan-enrollments/${current.id}/visits/${visit.id}/defer`,body={request_id:randomUUID(),reason:'Customer is away this service cycle.'};
      assert.equal((await request(path,{method:'POST',token:'plan-other',body})).status,404);
      assert.equal((await request(path,{method:'POST',body})).body.error,'plan_appointments_exist');
      await pool.query('DELETE FROM schedule_events WHERE id=$1',[jobID]);
      const restored=(await pool.query('SELECT * FROM agreement_plan_visits WHERE id=$1',[visit.id])).rows[0];assert.equal(restored.state,'due');assert.equal(restored.job_id,null);assert.ok(restored.job_history.some(entry=>entry.action==='appointment_deleted'));
      const beforePayments=(await pool.query('SELECT count(*)::int n FROM payment_records')).rows[0].n;
      const deferred=await Promise.all([1,2,3].map(()=>request(path,{method:'POST',body})));
      assert.ok(deferred.every(result=>result.status===200),JSON.stringify(deferred));assert.ok(deferred.every(result=>result.body.remaining_visits===3));
      const dates=deferred[0].body.visits;
      assert.equal(String(dates.find(item=>item.id===visit.id).due_date).slice(0,10),advancePlanDate(current.snapshot.next_service_date,config.service_interval,visit.sequence));
      assert.equal((await pool.query('SELECT schedule_offset FROM agreement_plan_visits WHERE id=$1',[visit.id])).rows[0].schedule_offset,1);
      assert.equal((await pool.query('SELECT count(*)::int n FROM payment_records')).rows[0].n,beforePayments);
      assert.equal((await pool.query("SELECT count(*)::int n FROM agreement_events WHERE agreement_id=$1 AND type='plan_visit_deferred'",[published.id])).rows[0].n,1);
      assert.equal((await request(path,{method:'POST',body:{...body,reason:'Changed request'}})).status,409);
    });
    await t.test('archive uses tenant-scoped indexed filters while details retain live states',async()=>{
      const archive=await installAgreementArchive({pool,service,startWorker:false});
      assert.ok(await archive.refresh()>0);
      const result=await request('/api/agreements?kind=quote&signing=submitted&plan=active');
      assert.equal(result.status,200,JSON.stringify(result.body));assert.equal(result.body.total,1);assert.equal(result.body.agreements[0].id,published.id);assert.equal(result.body.agreements[0].payments.balance_cents,50500);
      assert.equal((await request('/api/agreements?signing=submitted',{token:'plan-other'})).body.total,0);
      const beyond=await request('/api/agreements?signing=submitted&offset=100');assert.equal(beyond.body.agreements.length,0);assert.equal(beyond.body.total,3);
      assert.equal((await request('/api/agreements?from_date=2026-02-30')).status,400);
      assert.equal((await request('/api/agreements?from_date=2100-01-01')).body.total,0);
      const originalCreated=(await pool.query('SELECT created_at FROM quote_agreements WHERE id=$1',[published.id])).rows[0].created_at;
      await pool.query("UPDATE companies SET timezone='America/New_York' WHERE id=$1",[company]);
      await pool.query("UPDATE quote_agreements SET created_at='2026-03-09T03:30:00Z' WHERE id=$1",[published.id]);
      const localDay=await request('/api/agreements?kind=quote&from_date=2026-03-08&to_date=2026-03-08');assert.equal(localDay.status,200,JSON.stringify(localDay.body));assert.equal(localDay.body.total,1);assert.equal(localDay.body.date_filter_timezone,'America/New_York');
      assert.equal((await request('/api/agreements?kind=quote&from_date=2026-03-09&to_date=2026-03-09')).body.total,0);
      assert.equal((await request('/api/agreements?from_date=2026-03-09&to_date=2026-03-08')).status,400);
      await pool.query('UPDATE quote_agreements SET created_at=$2 WHERE id=$1',[published.id,originalCreated]);
      await pool.query("UPDATE payment_records SET status='pending' WHERE quote_id=$1",[quote]);
      assert.equal((await pool.query('SELECT dirty FROM agreement_archive_index WHERE agreement_id=$1',[published.id])).rows[0].dirty,true);
      await archive.refresh();
      assert.equal((await pool.query('SELECT dirty FROM agreement_archive_index WHERE agreement_id=$1',[published.id])).rows[0].dirty,false);
      await pool.query("UPDATE agreement_plan_enrollments SET state='cancellation_pending' WHERE id=$1",[enrollment.id]);
      assert.equal((await pool.query('SELECT dirty FROM agreement_archive_index WHERE agreement_id=$1',[published.id])).rows[0].dirty,true);
      await pool.query("UPDATE agreement_plan_enrollments SET state='active' WHERE id=$1",[enrollment.id]);
      await pool.query("UPDATE service_plans SET status='past_due' WHERE enrollment_id=$1",[enrollment.id]);
      await archive.refresh();
      const due=await request('/api/agreements?kind=quote&plan=past_due');assert.equal(due.status,200);assert.equal(due.body.agreements[0].id,published.id);
      assert.equal((await request('/api/agreements?plan=cancellation_pending')).status,200);
      await pool.query("UPDATE service_plans SET status='active' WHERE enrollment_id=$1",[enrollment.id]);
      await archive.refresh();
    });
    await t.test('secondary recipients never receive primary plan signing tokens or commercial mutation rights',async()=>{
      await pool.query("UPDATE quote_agreements SET snapshot=jsonb_set(snapshot,'{required_signers}','[\"customer\",\"customer_2\"]'::jsonb) WHERE id=$1",[published.id]);
      const row=(await pool.query('SELECT * FROM quote_agreements WHERE id=$1',[published.id])).rows[0],secondary=service.makeToken(row,'customer_2');
      const view=(await request(`/api/public/agreements/${secondary}`,{token:null})).body;assert.equal(view.viewer_role,'customer_2');assert.equal(view.plan.plan_agreement_url,null);
      assert.equal((await request(`/api/public/agreements/${secondary}/plan-offers`,{token:null})).body.offers.length,0);
      const secondarySession=(await request(`/api/public/agreements/${secondary}/session`,{token:null,method:'POST',body:{}})).body;
      const secondarySigned=(await request(`/api/public/agreements/${secondary}/sign`,{token:null,method:'POST',body:{request_id:randomUUID(),session_token:secondarySession.session_token,packet_hash:row.packet_hash,printed_name:'Second Customer',consent:true,signature:drawnSignature(),values:{}}}));
      assert.equal(secondarySigned.status,200,JSON.stringify(secondarySigned.body));
      assert.equal(secondarySigned.body.plan.plan_agreement_url,null);
      const completedSession=(await request(`/api/public/agreements/${secondary}/session`,{token:null,method:'POST',body:{}})).body;
      assert.equal(completedSession.completed,true);
      assert.equal(completedSession.agreement.plan.plan_agreement_url,null);
      assert.equal((await request(`/api/public/agreements/${secondary}/enrollments`,{method:'POST',token:null,body:{request_id:randomUUID(),tier_id:tier.tier_id,tier_version:1,offer_hash:offer.offer_hash}})).status,403);
      assert.equal((await request(`/api/public/agreements/${secondary}/enrollments/${enrollment.id}/reconcile`,{method:'POST',token:null,body:{}})).status,403);
      await pool.query("UPDATE quote_agreements SET snapshot=jsonb_set(snapshot,'{required_signers}','[\"customer\",\"customer_2\"]'::jsonb) WHERE id=$1",[enrollment.plan_agreement_id]);
      const planView=(await request(`/api/public/agreements/${secondary}/enrollments/${enrollment.id}`,{token:null})).body;
      assert.ok(planView.plan_agreement_url);assert.notEqual(planView.plan_agreement_url,enrollment.plan_agreement_url);
      const roleLink=planView.plan_agreement_url.split('/').at(-1);assert.equal((await request(`/api/public/agreements/${roleLink}`,{token:null})).body.viewer_role,'customer_2');
    });
    await t.test('returning customer keeps current tier first and replacement activates only after old cancellation',async()=>{
      await pool.query('UPDATE saved_services SET plan_eligible=true,archived_at=NULL WHERE id=$1',[windowID]);
      const adapter=await installAgreementPlanBilling({app:backend.app,pool,service,plans,env,getStripe:()=>null,startWorker:false});
      const newer=await request('/api/service-plan-tiers',{method:'POST',body:{configuration:{...config,name:'Monthly care',service_interval:{unit:'month',count:1},term:{kind:'ongoing'},discount:{type:'percent',value:2000}}}});assert.equal(newer.status,201);
      const choices=(await request(`/api/public/agreements/${token}/plan-offers`,{token:null})).body;
      assert.equal(choices.current_memberships.length,1);assert.ok(!choices.offers.some(choice=>choice.tier_id===tier.tier_id));
      const replacement=choices.offers.find(choice=>choice.tier_id===newer.body.tier_id);assert.equal(replacement.replaces.enrollment_id,enrollment.id);
      const selected=await request(`/api/public/agreements/${token}/enrollments`,{method:'POST',token:null,body:{request_id:randomUUID(),tier_id:replacement.tier_id,tier_version:replacement.tier_version,offer_hash:replacement.offer_hash}});assert.equal(selected.status,201,JSON.stringify(selected.body));
      assert.equal((await pool.query('SELECT status FROM service_plans WHERE id=$1',[choices.current_memberships[0].service_plan_id])).rows[0].status,'active');
      const terms=(await request(`/api/agreements/${selected.body.plan_agreement_id}`)).body;await sign(terms);
      const ready=await request(`/api/public/agreements/${token}/enrollments/${selected.body.id}/reconcile`,{method:'POST',token:null,body:{}});assert.equal(ready.status,200,JSON.stringify(ready.body));assert.equal(ready.body.state,'active');
      const live=(await pool.query("SELECT * FROM service_plans WHERE company_id=$1 AND status='active'",[company])).rows;assert.equal(live.length,1);assert.equal(live[0].plan_name,'Monthly care');
      assert.ok((await pool.query('SELECT canceled_at FROM agreement_plan_enrollments WHERE id=$1',[enrollment.id])).rows[0].canceled_at);

    });
  } finally {if(server)await new Promise(resolve=>server.close(resolve));if(pool)await pool.end();postgres.stop();}
});
