import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import express from 'express';
import {createCommsFixture} from './helpers/comms-fixture.js';
import {installCompanyComms} from '../company-comms/index.js';
import {installCollaboration} from '../company-comms/collaboration.js';
import {taskAccessSQL} from '../company-comms/tasks.js';

test('bounded workflows validate, preview, request approval and execute once with fresh access',{timeout:120000},async t=>{
 const f=await createCommsFixture(),{pool,ids,companies}=f;let core,collab,w,run;try{
  await pool.query("UPDATE employee_permissions SET permission_overrides=permission_overrides||'{\"communications.workflows\":true}' WHERE user_id=$1",[ids.alice]);const alice=await f.actor('alice'),bob=await f.actor('bob'),carol=await f.actor('carol');const app=express();core=await installCompanyComms({app,pool,authRequired:(_r,_s,n)=>n(),startWorker:false});collab=installCollaboration({app,pool,authRequired:(_r,_s,n)=>n(),messages:core.messages,notifications:core.notifications,startWorker:false});const room=await core.messages.create(alice,{client_key:randomUUID(),member_ids:[ids.bob]});
  const definition={trigger:'form',fields:[{id:'issue',label:'Issue',type:'text',required:true},{id:'urgent',label:'Urgent',type:'boolean',required:true},{id:'due_date',label:'Due date',type:'date',required:true}],conditions:[{field:'urgent',operator:'equals',value:true}],actions:[{type:'post_message',template:'Equipment issue: {{issue}}'},{type:'create_task',template:'Resolve {{issue}}',due_field:'due_date'},{type:'remind',due_field:'due_date',minutes_before:60}],approver_ids:[ids.bob]};
  await t.test('creation remains disabled and preview writes no messages, tasks or runs',async()=>{
   w=await collab.workflows.save(alice,room.id,null,{name:'Equipment requests',enabled:true,definition});assert.equal(w.enabled,false);const before=Number((await pool.query('SELECT count(*) FROM messages')).rows[0].count);const preview=await collab.workflows.submit(alice,w.id,{fields:{issue:'Pump failure',urgent:true,due_date:new Date(Date.now()+1800000).toISOString()},preview:true});assert.equal(preview.preview.actions.length,3);assert.equal(preview.preview.approval_required,true);assert.equal(Number((await pool.query('SELECT count(*) FROM messages')).rows[0].count),before);assert.equal(Number((await pool.query('SELECT count(*) FROM comms_workflow_runs')).rows[0].count),0);
   await assert.rejects(collab.workflows.submit(alice,w.id,{client_key:'disabled',fields:{issue:'Pump',urgent:true,due_date:new Date().toISOString()}}),e=>e.code==='workflow_disabled');await assert.rejects(collab.workflows.save(bob,null,w.id,{expected_revision:1,enabled:true}),e=>e.status===403);w=await collab.workflows.save(alice,null,w.id,{expected_revision:1,enabled:true});
  });
  await t.test('form validation, conditions and approval audience are enforced',async()=>{
   await assert.rejects(collab.workflows.submit(alice,w.id,{client_key:'bad',fields:{urgent:'yes'}}),e=>e.status===400);await assert.rejects(collab.workflows.submit(carol,w.id,{client_key:'outsider',fields:{}}),e=>e.status===404);
   const skipped=await collab.workflows.submit(alice,w.id,{client_key:'skip',fields:{issue:'Not urgent',urgent:false,due_date:new Date().toISOString()}});assert.equal(skipped.state,'skipped');
   run=await collab.workflows.submit(alice,w.id,{client_key:'equipment-one',fields:{issue:'Pump failure',urgent:true,due_date:new Date(Date.now()+1800000).toISOString()},assignee_ids:[ids.bob]});assert.equal(run.state,'pending');assert.equal((await collab.workflows.submit(alice,w.id,{client_key:'equipment-one',fields:{issue:'Pump failure',urgent:true,due_date:new Date().toISOString()}})).id,run.id);assert.equal(Number((await pool.query('SELECT count(*) FROM todo_tasks')).rows[0].count),0);assert.equal((await core.notifications.list(bob)).unread_count,1);await assert.rejects(collab.workflows.decide(alice,run.id,{expected_revision:1,action:'approve'}),e=>e.status===403);
  });
  await t.test('approval atomically posts with app identity, creates canonical task and schedules personal reminder',async()=>{
   const accepted=await collab.workflows.decide(bob,run.id,{expected_revision:1,action:'approve'});assert.equal(accepted.state,'approved');assert.equal(accepted.result.length,3);const again=await collab.workflows.decide(bob,run.id,{expected_revision:1,action:'approve'});assert.equal(again.state,'approved');assert.equal(Number((await pool.query('SELECT count(*) FROM todo_tasks')).rows[0].count),1);const post=(await pool.query("SELECT * FROM messages WHERE message_kind='workflow'")).rows[0];assert.match(post.body,/Workflow · Equipment requests/);assert.equal(post.sender_id,ids.alice);const task=(await pool.query('SELECT * FROM todo_tasks')).rows[0];assert.match(task.id,/^[0-9a-f-]{36}$/);assert.equal(task.title,'Resolve Pump failure');
   await collab.workflows.tick();await collab.workflows.tick();assert.equal(Number((await pool.query("SELECT count(*) FROM notifications WHERE kind='comms.workflow_reminder' AND user_id=$1",[ids.bob])).rows[0].count),1);
  });
  await t.test('changed workflow and lost requester access cannot run previously proposed actions',async()=>{
   const pending=await collab.workflows.submit(alice,w.id,{client_key:'stale',fields:{issue:'New proposal',urgent:true,due_date:new Date().toISOString()}});w=await collab.workflows.save(alice,null,w.id,{expected_revision:w.revision,name:'Revised equipment'});await assert.rejects(collab.workflows.decide(bob,pending.id,{expected_revision:1,action:'approve'}),e=>e.status===409);
   const lost=await collab.workflows.submit(alice,w.id,{client_key:'lost',fields:{issue:'Blocked proposal',urgent:true,due_date:new Date().toISOString()}});await pool.query("UPDATE employee_permissions SET permission_overrides=permission_overrides||'{\"communications.send\":false}' WHERE user_id=$1",[ids.alice]);await assert.rejects(collab.workflows.decide(bob,lost.id,{expected_revision:1,action:'approve'}),e=>e.status===403);assert.equal(Number((await pool.query("SELECT count(*) FROM messages WHERE body LIKE '%Blocked proposal%'")).rows[0].count),0);await pool.query("UPDATE employee_permissions SET permission_overrides=permission_overrides-'communications.send' WHERE user_id=$1",[ids.alice]);
  });
  await t.test('typed existing automation events create approval requests once and reject looped events',async()=>{
   await pool.query("CREATE TABLE automation_events(id uuid PRIMARY KEY,company_id uuid,event_type text,subject_id text,payload jsonb,occurred_at timestamptz DEFAULT now())");await pool.query("INSERT INTO schedule_events(id,company_id,title) VALUES('job-event',$1,'Job event')",[companies.a]);let typed=await collab.workflows.save(alice,room.id,null,{name:'Job event approval',definition:{trigger:'job.completed',fields:[],conditions:[],actions:[{type:'post_message',template:'Authorized job update'}],approver_ids:[ids.bob]}});typed=await collab.workflows.save(alice,null,typed.id,{expected_revision:1,enabled:true});
   await pool.query("INSERT INTO automation_events(id,company_id,event_type,subject_id,payload) VALUES($1,$2,'job.completed','job-event','{}'),($3,$2,'job.completed','job-event','{\"automation_event_depth\":1}')",[randomUUID(),companies.a,randomUUID()]);await collab.workflows.tick();await collab.workflows.tick();const history=await collab.workflows.history(alice,typed.id);assert.equal(history.length,1);assert.equal(history[0].state,'pending');assert.equal(Number((await pool.query("SELECT count(*) FROM messages WHERE body LIKE '%Authorized job update%'")).rows[0].count),0);
  });
  await t.test('workflow file references are shared only on submit and retain source restrictions in review and tasks',async()=>{
   const contact=randomUUID(),quote=randomUUID(),asset=await f.asset();await pool.query('INSERT INTO contacts(id,company_id,name) VALUES($1,$2,$3)',[contact,companies.a,'Workflow customer']);await pool.query('INSERT INTO quotes(id,company_id,contact_id,title) VALUES($1,$2,$3,$4)',[quote,companies.a,contact,'Workflow quote']);await pool.query('UPDATE stored_files SET source_protected=true WHERE id=$1',[asset]);await pool.query("INSERT INTO comms_asset_provenance(asset_id,company_id,source_type,source_id,context_type) VALUES($1,$2,'quote',$3,'quote')",[asset,companies.a,quote]);
   const payload={client_key:randomUUID(),fields:{issue:'Protected file request',urgent:true,due_date:new Date(Date.now()+86400000).toISOString()},asset_ids:[asset],assignee_ids:[ids.bob]};await collab.workflows.submit(alice,w.id,{...payload,preview:true});assert.equal((await pool.query("SELECT 1 FROM comms_asset_grants WHERE asset_id=$1 AND source_type='workflow_run'",[asset])).rowCount,0);
   const pending=await collab.workflows.submit(alice,w.id,payload);const review=await collab.workflows.getRun(bob,pending.id);assert.equal(review.attachments[0].id,asset);assert.equal('object_key' in review.attachments[0],false);await pool.query(`UPDATE employee_permissions SET permission_overrides=permission_overrides||'{"quotes.view":false}' WHERE user_id=$1`,[ids.bob]);const hidden=await collab.workflows.getRun(bob,pending.id);assert.deepEqual(hidden,{id:pending.id,state:'pending',revision:1,accessible:false,text:'No Access'});await assert.rejects(collab.workflows.decide(bob,pending.id,{expected_revision:1,action:'approve'}),e=>e.status===403);await pool.query(`UPDATE employee_permissions SET permission_overrides=permission_overrides||'{"quotes.view":true}' WHERE user_id=$1`,[ids.bob]);
   const approved=await collab.workflows.decide(bob,pending.id,{expected_revision:1,action:'approve'});assert.equal(approved.state,'approved');const task=approved.result.find(x=>x.type==='task');await pool.query(`UPDATE employee_permissions SET permission_overrides=permission_overrides||'{"quotes.view":false}' WHERE user_id=$1`,[ids.bob]);const current=await f.actor('bob');assert.equal((await pool.query(`SELECT t.id FROM todo_tasks t WHERE t.id=$3 AND ${taskAccessSQL(current,'t')}`,[current.userId,current.companyId,task.id])).rowCount,0);
  });
 }finally{collab?.stop();core?.stop();await f.close();}
});
