import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import {randomUUID} from 'node:crypto';
import {createCommsFixture} from './helpers/comms-fixture.js';
import {installCompanyComms} from '../company-comms/index.js';
import {installCollaboration} from '../company-comms/collaboration.js';
import {createTaskInTransaction,taskAccessSQL} from '../company-comms/tasks.js';
import {mutate} from '../company-comms/access.js';
import {storagePredicate} from '../company-comms/assets.js';
import {enforceSensitiveRoute} from '../permission-routes.js';
import {installCallsSchema} from '../company-comms/calls/schema.js';
import {installProcessingSchema} from '../company-comms/calls/processing.js';

const rejects=(p,codes=[403,404])=>assert.rejects(p,e=>codes.includes(e.status));
test('collaboration uses real conversations, canonical tasks, durable sends and scoped search',{timeout:120000},async t=>{
 const f=await createCommsFixture(),{pool,ids,companies}=f;let server,core,collab,room,note,sourceMessage,poll,task;const actors=Object.fromEntries(await Promise.all(Object.keys(ids).map(async k=>[k,await f.actor(k)])));
 const app=express();app.use(express.json());const auth=async(req,res,next)=>{try{const name=req.get('Authorization');if(!ids[name])return res.status(401).json({error:'auth'});Object.assign(req,await f.actor(name));if(enforceSensitiveRoute(req,res))next();}catch(e){res.status(e.status||503).json({error:e.code||'unavailable'});}};
 try{
  core=await installCompanyComms({app,pool,authRequired:auth,startWorker:false});collab=installCollaboration({app,pool,authRequired:auth,messages:core.messages,notifications:core.notifications,startWorker:false});room=await core.messages.create(actors.alice,{client_key:randomUUID(),member_ids:[ids.bob]});sourceMessage=await core.messages.send(actors.alice,room.id,{client_key:randomUUID(),body:'Private operational source'});
  await t.test('notes persist formatting, version conflicts, content edit authority and revocable asset references',async()=>{
   const asset=await f.asset();note=await collab.notes.save(actors.alice,room.id,null,{client_key:'note-once',title:'PRIVATE SOP',body:'## Checklist\n- [ ] Inspect equipment\n[Manual](https://example.invalid/manual)',asset_ids:[asset]});assert.equal(note.attachments[0].id,asset);assert.equal(note.editor_name,'alice');assert.equal((await collab.notes.save(actors.alice,room.id,null,{client_key:'note-once',title:'retry'})).id,note.id);
   await rejects(collab.notes.get(actors.carol,note.id));await rejects(collab.notes.get(actors.owner,note.id));const before=await collab.notes.get(actors.bob,note.id);assert.equal(before.title,'PRIVATE SOP');
   const updated=await collab.notes.save(actors.bob,null,note.id,{expected_revision:1,body:'Updated checklist'});assert.equal(updated.revision,2);assert.equal(updated.editor_name,'bob');assert.equal(updated.attachments[0].id,asset);await rejects(collab.notes.save(actors.alice,null,note.id,{expected_revision:1,body:'stale'}),[409]);const versions=await collab.notes.versions(actors.alice,note.id);assert.equal(versions[0].body.includes('- [ ]'),true);assert.equal(versions[0].editor_id,ids.alice);assert.equal(versions[0].editor_name,'alice');
   await pool.query("UPDATE employee_permissions SET permission_overrides=permission_overrides||'{\"communications.notes\":false}' WHERE user_id=$1",[ids.bob]);await rejects(collab.notes.save(actors.bob,null,note.id,{expected_revision:2,body:'not allowed'}));assert.equal((await collab.notes.get(actors.bob,note.id)).body,'Updated checklist');
   note=await collab.notes.save(actors.alice,null,note.id,{expected_revision:2,asset_ids:[]});const actor=await f.actor('bob'),acl=await storagePredicate(pool,actor);assert.equal((await pool.query(`SELECT 1 FROM stored_files f WHERE f.id=$3 AND (${acl})`,[actor.userId,actor.companyId,asset])).rowCount,0);
  });
  await t.test('protected note attachments hide all metadata after source capability revocation',async()=>{
   const quote=randomUUID(),contact=randomUUID(),asset=await f.asset();await pool.query('INSERT INTO contacts(id,company_id,name) VALUES($1,$2,$3)',[contact,companies.a,'Note customer']);await pool.query('INSERT INTO quotes(id,company_id,contact_id,title,total_cents) VALUES($1,$2,$3,$4,1000)',[quote,companies.a,contact,'Protected note quote']);await pool.query('UPDATE stored_files SET source_protected=true WHERE id=$1',[asset]);await pool.query("INSERT INTO comms_asset_provenance(asset_id,company_id,source_type,source_id,context_type) VALUES($1,$2,'quote',$3,'quote')",[asset,companies.a,quote]);
   const protectedNote=await collab.notes.save(actors.alice,room.id,null,{client_key:randomUUID(),title:'Shared file',asset_ids:[asset]});assert.equal((await collab.notes.get(actors.bob,protectedNote.id)).attachments[0].id,asset);await pool.query(`UPDATE employee_permissions SET permission_overrides=permission_overrides||'{"quotes.view":false}' WHERE user_id=$1`,[ids.bob]);assert.deepEqual((await collab.notes.get(actors.bob,protectedNote.id)).attachments,[{accessible:false,text:'No Access'}]);await pool.query(`UPDATE employee_permissions SET permission_overrides=permission_overrides||'{"quotes.view":true}' WHERE user_id=$1`,[ids.bob]);
  });
  await t.test('polls enforce membership, single/multiple choice, retry voting and author close',async()=>{
   const ordinary=await core.messages.send(actors.alice,room.id,{client_key:'text-not-poll',body:'Original text'});await rejects(collab.polls.create(actors.alice,room.id,{client_key:'text-not-poll',question:'Overwrite?',options:['Yes','No']}),[409]);assert.equal((await pool.query('SELECT body,message_kind FROM messages WHERE id=$1',[ordinary.id])).rows[0].body,'Original text');assert.equal((await pool.query('SELECT 1 FROM comms_polls WHERE message_id=$1',[ordinary.id])).rowCount,0);
   poll=await collab.polls.create(actors.alice,room.id,{client_key:'poll-once',question:'Which shift?',options:['Early','Late'],multiple:false});assert.equal((await collab.polls.create(actors.alice,room.id,{client_key:'poll-once',question:'Which shift?',options:['Early','Late']})).message_id,poll.message_id);await rejects(collab.polls.get(actors.carol,poll.message_id));await rejects(collab.polls.vote(actors.bob,poll.message_id,{option_ids:poll.options.map(x=>x.id)}),[400]);await collab.polls.vote(actors.bob,poll.message_id,{option_ids:[poll.options[0].id]});await collab.polls.vote(actors.bob,poll.message_id,{option_ids:[poll.options[0].id]});assert.equal((await collab.polls.get(actors.alice,poll.message_id)).voter_count,1);await rejects(collab.polls.close(actors.bob,poll.message_id));await collab.polls.close(actors.alice,poll.message_id);await rejects(collab.polls.vote(actors.bob,poll.message_id,{option_ids:[]}),[409]);assert.equal((await core.messages.history(actors.alice,room.id)).messages.find(x=>x.id===poll.message_id).message_kind,'poll');
  });
  await t.test('scheduled messages edit/cancel, send once and revalidate membership at delivery',async()=>{
   const future=new Date(Date.now()+60000).toISOString();let schedule=await collab.scheduled.save(actors.alice,room.id,null,{client_key:'schedule-once',body:'Later message',send_at:future,timezone:'America/New_York'});assert.equal((await collab.scheduled.list(actors.bob,room.id)).length,0);schedule=await collab.scheduled.save(actors.alice,null,schedule.id,{expected_revision:1,body:'Revised later'});await rejects(collab.scheduled.save(actors.alice,null,schedule.id,{expected_revision:1,body:'lost edit'}),[409]);
   await pool.query("UPDATE comms_scheduled_messages SET send_at=now()-interval '1 second' WHERE id=$1",[schedule.id]);await Promise.all([collab.scheduled.tick(),collab.scheduled.tick()]);assert.equal(Number((await pool.query("SELECT count(*) FROM messages WHERE client_key=$1",['scheduled:'+schedule.id])).rows[0].count),1);assert.equal((await collab.scheduled.list(actors.alice,room.id))[0].status,'sent');
   const canceled=await collab.scheduled.save(actors.alice,room.id,null,{client_key:'schedule-cancel',body:'Canceled',send_at:future});await collab.scheduled.cancel(actors.alice,canceled.id,{expected_revision:1});await pool.query("UPDATE comms_scheduled_messages SET send_at=now()-interval '1 second' WHERE id=$1",[canceled.id]);await collab.scheduled.tick();assert.equal((await pool.query('SELECT status FROM comms_scheduled_messages WHERE id=$1',[canceled.id])).rows[0].status,'canceled');
   const lost=await core.messages.create(actors.alice,{client_key:randomUUID(),member_ids:[ids.carol],force_new:true});const pending=await collab.scheduled.save(actors.carol,lost.id,null,{client_key:'schedule-lost',body:'Must never deliver',send_at:future});await core.messages.members(actors.carol,lost.id,{remove_user_ids:[ids.carol],expected_revision:1});await pool.query("UPDATE comms_scheduled_messages SET send_at=now()-interval '1 second' WHERE id=$1",[pending.id]);await collab.scheduled.tick();assert.equal((await pool.query('SELECT status FROM comms_scheduled_messages WHERE id=$1',[pending.id])).rows[0].status,'failed');assert.equal(Number((await pool.query("SELECT count(*) FROM messages WHERE body='Must never deliver'")).rows[0].count),0);
  });
  await t.test('scheduled delivery rechecks source feature access as well as conversation membership',async()=>{
   const quote=randomUUID(),contact=randomUUID();await pool.query('INSERT INTO contacts(id,company_id,name) VALUES($1,$2,$3)',[contact,companies.a,'Scheduled customer']);await pool.query('INSERT INTO quotes(id,company_id,contact_id,title,total_cents) VALUES($1,$2,$3,$4,1000)',[quote,companies.a,contact,'Revoked quote']);await pool.query(`UPDATE employee_permissions SET permission_overrides=permission_overrides||'{"quotes.share":true,"communications.share":true}' WHERE user_id=$1`,[ids.alice]);const pending=await collab.scheduled.save(actors.alice,room.id,null,{client_key:randomUUID(),body:'Blocked quote share',cards:[{source_type:'quote',source_id:quote}],send_at:new Date(Date.now()+60000).toISOString()});await pool.query(`UPDATE employee_permissions SET permission_overrides=permission_overrides||'{"quotes.view":false}' WHERE user_id=$1`,[ids.alice]);await pool.query("UPDATE comms_scheduled_messages SET send_at=now()-interval '1 second' WHERE id=$1",[pending.id]);await collab.scheduled.tick();assert.equal((await pool.query('SELECT status FROM comms_scheduled_messages WHERE id=$1',[pending.id])).rows[0].status,'failed');assert.equal((await pool.query('SELECT id FROM messages WHERE client_key=$1',['scheduled:'+pending.id])).rowCount,0);await pool.query(`UPDATE employee_permissions SET permission_overrides=permission_overrides||'{"quotes.view":true}' WHERE user_id=$1`,[ids.alice]);
  });
  await t.test('message-to-task creates canonical data once and enforces assignee/source privacy',async()=>{
   const body={client_key:'task-once',title:'PRIVATE TASK',assignee_ids:[ids.bob],due_date:new Date(Date.now()+86400000).toISOString()};task=await mutate(pool,actors.alice,(db,a)=>createTaskInTransaction(db,a,sourceMessage.id,body));const retry=await mutate(pool,actors.alice,(db,a)=>createTaskInTransaction(db,a,sourceMessage.id,body));assert.equal(retry.id,task.id);assert.equal((await pool.query('SELECT title FROM todo_tasks WHERE id=$1',[task.id])).rows[0].title,'PRIVATE TASK');await rejects(mutate(pool,actors.alice,(db,a)=>createTaskInTransaction(db,a,sourceMessage.id,{...body,client_key:'bad-task',assignee_ids:[ids.carol]})));
   for(const who of ['alice','bob','carol','owner','foreign']){const a=await f.actor(who);const rows=await pool.query(`SELECT * FROM todo_tasks t WHERE t.id=$3 AND ${taskAccessSQL(a,'t')}`,[a.userId,a.companyId,task.id]);assert.equal(rows.rowCount,['alice','bob'].includes(who)?1:0,who);}
  });
  await t.test('search applies private ACLs before snippets, attachment and author filters or cursors',async()=>{
   const mine=await collab.search.search(actors.alice,{search:'PRIVATE'});assert.ok(mine.results.some(x=>x.type==='note'));const other=await collab.search.search(actors.carol,{search:'PRIVATE'});assert.equal(other.results.length,0);assert.equal((await collab.search.search(actors.owner,{search:'PRIVATE'})).results.length,0);assert.equal((await collab.search.search(actors.foreign,{search:'PRIVATE'})).results.length,0);
   const pages=[];let cursor;do{const page=await collab.search.search(actors.alice,{type:'message',conversation_id:room.id,limit:1,cursor});pages.push(...page.results);cursor=page.next_cursor;}while(cursor);assert.equal(new Set(pages.map(x=>x.id)).size,pages.length);assert.ok(pages.length>=3);await rejects(collab.search.search(actors.carol,{type:'file',conversation_id:room.id}));
  });
  await t.test('followed and link browsing applies per-user state, source conversation ACL and filters before results',async()=>{
   const link=await core.messages.send(actors.alice,room.id,{client_key:randomUUID(),body:'Manual https://example.invalid/crew'});await core.messages.personal(actors.bob,link.id,{followed:true});const mine=await collab.search.search(actors.bob,{followed:'true'});assert.ok(mine.results.some(x=>x.id===link.id));assert.ok(mine.results.every(x=>x.type==='message'));assert.equal((await collab.search.search(actors.alice,{followed:'true'})).results.some(x=>x.id===link.id),false);const links=await collab.search.search(actors.bob,{has_link:'true',conversation_id:room.id});assert.ok(links.results.some(x=>x.id===link.id));assert.ok(links.results.every(x=>x.type==='message'&&/https?:\/\/|www[.]/i.test(x.snippet)));assert.equal((await collab.search.search(actors.carol,{has_link:'true'})).results.some(x=>x.id===link.id),false);await rejects(collab.search.search(actors.carol,{followed:'true',conversation_id:room.id}));await core.messages.edit(actors.alice,link.id,{expected_revision:1},true);assert.equal((await collab.search.search(actors.bob,{followed:'true',has_link:'true'})).results.some(x=>x.id===link.id),false);
  });
  await t.test('derived recording tasks retain transitive readiness and original asset source checks',async()=>{
   await installCallsSchema(pool);await installProcessingSchema(pool);const call=randomUUID(),recording=randomUUID(),job=randomUUID(),review=randomUUID(),asset=await f.asset('alice','audio');
   await pool.query(`UPDATE employee_permissions SET permission_overrides=permission_overrides||'{"communications.ai":true}' WHERE user_id=ANY($1::uuid[])`,[[ids.alice,ids.bob]]);
   await pool.query("INSERT INTO comms_call_sessions(id,company_id,conversation_id,creator_user_id,host_user_id,kind,media,room_name,status,ended_at) VALUES($1,$2,$3,$4,$4,'meeting','audio',$5,'ended',now())",[call,companies.a,room.id,ids.alice,'test_'+call]);
   await pool.query("INSERT INTO comms_call_recordings(id,call_id,company_id,requested_by,object_key,asset_id,media,status) VALUES($1,$2,$3,$4,$5,$6,'audio','ready')",[recording,call,companies.a,ids.alice,'test/'+asset,asset]);
   await pool.query("INSERT INTO comms_processing_jobs(id,company_id,recording_id,requested_by,kind,status) VALUES($1,$2,$3,$4,'summary','ready')",[job,companies.a,recording,ids.alice]);await pool.query("INSERT INTO comms_review_actions(id,job_id,company_id,title,detail,segment_ids,state) VALUES($1,$2,$3,'Approved','', '[]','approved')",[review,job,companies.a]);
   const taskBody=()=>({client_key:randomUUID(),title:'Derived recording task',assignee_ids:[ids.bob]});const parent=await mutate(pool,actors.alice,(db,a)=>createTaskInTransaction(db,a,{conversation_id:room.id,source_type:'recording_review',source_id:review,requirements:['communications.ai']},taskBody()));
   const share=async taskID=>core.messages.send(actors.alice,room.id,{client_key:randomUUID(),cards:[{source_type:'task',source_id:taskID}]});const firstMessage=await share(parent.id),child=await mutate(pool,actors.alice,(db,a)=>createTaskInTransaction(db,a,firstMessage.id,taskBody()));const secondMessage=await share(child.id),grandchild=await mutate(pool,actors.alice,(db,a)=>createTaskInTransaction(db,a,secondMessage.id,taskBody()));
   const visible=async()=>{const a=await f.actor('bob');return (await pool.query(`SELECT t.id FROM todo_tasks t WHERE t.id=ANY($3::text[]) AND ${taskAccessSQL(a,'t')}`,[a.userId,a.companyId,[parent.id,child.id,grandchild.id]])).rowCount;};assert.equal(await visible(),3);
   assert.ok((await pool.query('SELECT source_dependencies FROM comms_task_links WHERE task_id=$1',[grandchild.id])).rows[0].source_dependencies.some(x=>x.source_type==='recording_review'&&x.source_id===review));
   await pool.query("UPDATE comms_processing_jobs SET status='canceled' WHERE id=$1",[job]);assert.equal(await visible(),0);await rejects(mutate(pool,actors.alice,(db,a)=>createTaskInTransaction(db,a,secondMessage.id,taskBody())));await pool.query("UPDATE comms_processing_jobs SET status='ready' WHERE id=$1",[job]);assert.equal(await visible(),3);
   await pool.query('UPDATE comms_task_links SET revoked_at=now() WHERE task_id=$1',[parent.id]);assert.equal(await visible(),0);await pool.query('UPDATE comms_task_links SET revoked_at=NULL WHERE task_id=$1',[parent.id]);await pool.query("UPDATE stored_files SET cloud_status='deleted',deleted_at=now() WHERE id=$1",[asset]);assert.equal(await visible(),0);
   const quote=randomUUID(),contact=randomUUID(),exportAsset=await f.asset();await pool.query('INSERT INTO contacts(id,company_id,name) VALUES($1,$2,$3)',[contact,companies.a,'Derived customer']);await pool.query('INSERT INTO quotes(id,company_id,contact_id,title) VALUES($1,$2,$3,$4)',[quote,companies.a,contact,'Derived quote']);await pool.query('UPDATE stored_files SET source_protected=true WHERE id=$1',[exportAsset]);await pool.query("INSERT INTO comms_asset_provenance(asset_id,company_id,source_type,source_id,context_type) VALUES($1,$2,'quote',$3,'quote')",[exportAsset,companies.a,quote]);
   const attached=await core.messages.send(actors.alice,room.id,{client_key:randomUUID(),asset_ids:[exportAsset]});const derived=await mutate(pool,actors.alice,(db,a)=>createTaskInTransaction(db,a,attached.id,taskBody()));await pool.query(`UPDATE employee_permissions SET permission_overrides=permission_overrides||'{"quotes.view":false}' WHERE user_id=$1`,[ids.bob]);const bob=await f.actor('bob');assert.equal((await pool.query(`SELECT t.id FROM todo_tasks t WHERE t.id=$3 AND ${taskAccessSQL(bob,'t')}`,[bob.userId,bob.companyId,derived.id])).rowCount,0);await pool.query(`UPDATE employee_permissions SET permission_overrides=permission_overrides||'{"quotes.view":true}' WHERE user_id=$1`,[ids.bob]);
  });
  await t.test('personal reminders deduplicate and revoked access cancels delivery',async()=>{
   await core.messages.personal(actors.bob,sourceMessage.id,{saved:true,remind_at:new Date(Date.now()-1000).toISOString()});await collab.tick();await collab.tick();assert.equal(Number((await pool.query("SELECT count(*) FROM notifications WHERE user_id=$1 AND kind='comms.reminder'",[ids.bob])).rows[0].count),1);assert.ok((await collab.saved(actors.bob)).items.some(x=>x.id===sourceMessage.id));
   await core.messages.personal(actors.bob,sourceMessage.id,{remind_at:new Date(Date.now()-1000).toISOString()});const rev=(await pool.query('SELECT revision FROM conversations WHERE id=$1',[room.id])).rows[0].revision;await core.messages.members(actors.bob,room.id,{remove_user_ids:[ids.bob],expected_revision:rev});await collab.tick();assert.equal(Number((await pool.query("SELECT count(*) FROM notifications WHERE user_id=$1 AND kind='comms.reminder'",[ids.bob])).rows[0].count),1);assert.equal((await collab.saved(actors.bob)).items.length,0);const actor=await f.actor('bob');assert.equal((await pool.query(`SELECT * FROM todo_tasks t WHERE t.id=$3 AND ${taskAccessSQL(actor,'t')}`,[actor.userId,actor.companyId,task.id])).rowCount,0);
  });
  await t.test('installed HTTP collaboration routes return data and deny unauthorized access',async()=>{
   server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));const origin='http://127.0.0.1:'+server.address().port;const response=await fetch(origin+'/api/comms/notes/'+note.id,{headers:{Authorization:'alice'}});assert.equal(response.status,200);assert.equal((await response.json()).title,'PRIVATE SOP');assert.equal((await fetch(origin+'/api/comms/notes/'+note.id,{headers:{Authorization:'carol'}})).status,404);assert.equal((await fetch(origin+'/api/comms/search?search=PRIVATE',{headers:{Authorization:'carol'}})).status,200);const templates=await fetch(origin+'/api/comms/templates',{headers:{Authorization:'alice'}});assert.equal((await templates.json()).templates.length,5);
  });
 }finally{collab?.stop();core?.stop();if(server)await new Promise(resolve=>server.close(resolve));await f.close();}
});
