import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {createCommsFixture} from './helpers/comms-fixture.js';import {installNotesSchema} from '../notes/schema.js';import {createNotesWorkspace} from '../notes/pages.js';import {createNotesTasks} from '../notes/tasks.js';import {taskAccessSQL,validateTaskAudience} from '../company-comms/tasks.js';
test('explicit checklist conversion creates one canonical task and retains note access for reads and reassignment',{timeout:120000},async()=>{
 const f=await createCommsFixture();try{await installNotesSchema(f.pool);await f.pool.query(`UPDATE employee_permissions SET permission_overrides=permission_overrides||'{"notes.view":true,"notes.create":true,"notes.share":true}'::jsonb WHERE user_id=ANY($1::uuid[])`,[[f.ids.alice,f.ids.bob]]);const alice=await f.actor('alice'),bob=await f.actor('bob'),owner=await f.actor('owner'),notes=createNotesWorkspace({pool:f.pool}),tasks=createNotesTasks({pool:f.pool,notes});let page=await notes.create(alice,{id:randomUUID(),title:'Private tasks'}),block=page.blocks[0];page=await notes.editBlocks(alice,page.page.id,{client_key:randomUUID(),operations:[{id:block.id,type:'checklist',expected_revision:1,position:0,payload:{text:'Buy test supplies'}}]});const body={client_key:randomUUID(),confirmed:true,expected_revision:2,assignee_ids:[alice.userId]};await assert.rejects(tasks.convert(alice,page.page.id,block.id,{...body,confirmed:false}),e=>e.status===400);await assert.rejects(tasks.convert(alice,page.page.id,block.id,{...body,assignee_ids:[bob.userId]}),e=>e.status===404);
 const result=await tasks.convert(alice,page.page.id,block.id,body);assert.equal((await tasks.convert(alice,page.page.id,block.id,body)).task_id,result.task_id);assert.equal((await f.pool.query('SELECT count(*)::int AS n FROM todo_tasks')).rows[0].n,1);assert.equal((await notes.get(alice,page.page.id)).blocks[0].type,'task');
 const visible=async actor=>(await f.pool.query(`SELECT id FROM todo_tasks WHERE ${taskAccessSQL(actor)}`,[actor.userId,actor.companyId])).rows;
 assert.equal((await visible(alice)).length,1);assert.equal((await visible(owner)).length,0);const link=(await f.pool.query('SELECT * FROM comms_task_links WHERE task_id=$1',[result.task_id])).rows[0];await assert.rejects(validateTaskAudience(f.pool,alice,link,[bob.userId]),e=>e.status===404);
 const current=await notes.get(alice,page.page.id);await notes.share(alice,page.page.id,{expected_revision:current.page.revision,members:[{user_id:bob.userId,role:'viewer'}]});await validateTaskAudience(f.pool,alice,link,[bob.userId]);assert.equal((await visible(bob)).length,1);
 const shared=await notes.get(alice,page.page.id);await notes.share(alice,page.page.id,{expected_revision:shared.page.revision,members:[]});assert.equal((await visible(bob)).length,0);
 }finally{await f.close();}
});
