import {createStorageService} from '../media-storage/service.js';import {storagePredicate} from '../company-comms/assets.js';import {createConversationService} from '../company-comms/messages.js';
import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {createCommsFixture} from './helpers/comms-fixture.js';import {installNotesSchema} from '../notes/schema.js';import {createNotesWorkspace} from '../notes/pages.js';import {createNotesExports} from '../notes/exports.js';
test('export contexts reauthorize all content and storage copies exclude independently protected details',{timeout:120000},async()=>{
 const f=await createCommsFixture();try{await installNotesSchema(f.pool);const owner=await f.actor('owner');await f.pool.query(`UPDATE employee_permissions SET permission_overrides=permission_overrides||'{"notes.view":true,"notes.export":true}'::jsonb WHERE user_id=$1`,[f.ids.bob]);const bob=await f.actor('bob'),notes=createNotesWorkspace({pool:f.pool}),exports=createNotesExports({pool:f.pool});
 const note=await notes.create(owner,{id:randomUUID(),title:'Export'}),privateNote=await notes.create(owner,{id:randomUUID(),title:'PRIVATE EXPORT SOURCE'});await notes.editBlocks(owner,note.page.id,{client_key:randomUUID(),operations:[{id:note.blocks[0].id,type:'paragraph',position:0,payload:{text:'Own text'},expected_revision:1},{id:randomUUID(),type:'page_link',position:1,payload:{target_id:privateNote.page.id},expected_revision:0}]});
 const ownerExport=await exports.context(owner,note.page.id);assert.equal(JSON.stringify(ownerExport).includes('PRIVATE EXPORT SOURCE'),true);const storage=await exports.context(owner,note.page.id,'storage');assert.equal(JSON.stringify(storage).includes('PRIVATE EXPORT SOURCE'),false);assert.equal(storage.blocks[0].payload.text,'Own text');assert.equal(storage.version,(await exports.context(owner,note.page.id,'storage')).version);
 const current=await notes.get(owner,note.page.id);await notes.share(owner,note.page.id,{expected_revision:current.page.revision,members:[{user_id:bob.userId,role:'viewer'}]});const shared=await exports.context(bob,note.page.id);assert.equal(JSON.stringify(shared).includes('PRIVATE EXPORT SOURCE'),false);assert.equal(shared.blocks[1].accessible,false);await assert.rejects(exports.context(bob,privateNote.page.id),e=>e.status===404);await assert.rejects(exports.reserve(owner,note.page.id,{}),e=>e.status===503);
 }finally{await f.close();}
});

test('canonical Storage export reservation is idempotent, source-protected and revoked with note membership',{timeout:120000},async()=>{
 const f=await createCommsFixture();try{await installNotesSchema(f.pool);await f.pool.query(`UPDATE employee_permissions SET permission_overrides=permission_overrides||'{"notes.view":true,"notes.export":true}'::jsonb WHERE user_id=$1`,[f.ids.bob]);const owner=await f.actor('owner'),bob=await f.actor('bob'),notes=createNotesWorkspace({pool:f.pool}),storage=createStorageService({pool:f.pool,bucket:{},accessPredicate:storagePredicate}),exports=createNotesExports({pool:f.pool,storage});
 let page=await notes.create(owner,{id:randomUUID(),title:'Storage copy'});page=await notes.share(owner,page.page.id,{expected_revision:page.page.revision,members:[{user_id:bob.userId,role:'viewer'}]});const context=await exports.context(owner,page.page.id,'storage'),id=randomUUID(),body={version:context.version,format:'pdf',file:{id,original_filename:'Note.pdf',mime_type:'application/pdf',byte_size:100}};
 const result=await exports.reserve(owner,page.page.id,body);assert.equal(result.file.source_protected,true);assert.equal(result.file.visibility,'private');assert.equal((await exports.reserve(owner,page.page.id,body)).file.id,id);await f.pool.query("UPDATE stored_files SET cloud_status='active' WHERE id=$1",[id]);
 const comms=createConversationService({pool:f.pool}),conversation=await comms.create(owner,{client_key:randomUUID(),member_ids:[bob.userId]});await comms.send(owner,conversation.id,{client_key:randomUUID(),body:'Note export',asset_ids:[id]});assert.equal((await storage.get(bob,id)).id,id);
 await notes.share(owner,page.page.id,{expected_revision:page.page.revision,members:[]});await assert.rejects(storage.get(bob,id),e=>e.status===404);assert.equal((await storage.get(owner,id)).id,id);assert.equal((await f.pool.query('SELECT 1 FROM stored_files WHERE id=$1',[id])).rowCount,1);
 }finally{await f.close();}
});
