import {createNotesDatabases} from '../notes/databases.js';
import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {createCommsFixture} from './helpers/comms-fixture.js';import {installNotesSchema} from '../notes/schema.js';import {createNotesWorkspace} from '../notes/pages.js';import {createNotesCollections} from '../notes/collections.js';
test('templates clone canonical structure privately, expand safe variables and recheck source access; smart folders and backlinks obey ACL',{timeout:120000},async()=>{
 const f=await createCommsFixture();try{await installNotesSchema(f.pool);const owner=await f.actor('owner');await f.pool.query(`UPDATE employee_permissions SET permission_overrides=permission_overrides||'{"notes.view":true,"notes.create":true}'::jsonb WHERE user_id=$1`,[f.ids.bob]);const bob=await f.actor('bob'),notes=createNotesWorkspace({pool:f.pool}),collections=createNotesCollections({pool:f.pool,notes});
 assert.equal((await collections.templates(owner)).templates.length,12);
 const id=randomUUID();await collections.instantiate(owner,'meeting',{id});const meeting=await notes.get(owner,id);assert.equal(meeting.page.visibility,'private');assert.equal(meeting.blocks.some(b=>b.payload.text.includes('{{date}}')),false);assert.equal(meeting.blocks.some(b=>b.type==='checklist'),true);await collections.instantiate(owner,'meeting',{id});assert.equal((await notes.get(owner,id)).blocks.length,meeting.blocks.length);await assert.rejects(notes.get(bob,id),e=>e.status===404);
 const source=await notes.create(owner,{id:randomUUID(),title:'Private template'});const child=await notes.create(owner,{id:randomUUID(),parent_id:source.page.id,title:'Child'});const block=randomUUID();await notes.editBlocks(owner,child.page.id,{client_key:randomUUID(),operations:[{id:block,type:'paragraph',position:1,expected_revision:0,payload:{text:'{{creator}} · {{company}}'}}]});const template=await collections.saveTemplate(owner,{page_id:source.page.id,title:'Reusable'});assert.equal((await collections.templates(bob)).templates.length,12);await assert.rejects(collections.instantiate(bob,template.id,{id:randomUUID()}),e=>e.status===404);
 const clone=await collections.instantiate(owner,template.id,{id:randomUUID()});const children=await notes.list(owner,{parent_id:clone.id});assert.equal(children.pages.length,1);assert.notEqual(children.pages[0].id,child.page.id);assert.equal(children.pages[0].inherit_access,true);assert.equal((await notes.get(owner,children.pages[0].id)).blocks.length,2);
 const db=createNotesDatabases({pool:f.pool,notes});const sourceDB=await notes.create(owner,{id:randomUUID(),kind:'database',parent_id:source.page.id,title:'Checklist database'});await db.configure(owner,sourceDB.page.id,{expected_revision:0,columns:[{id:'title',name:'Name',type:'title'},{id:'relation',name:'Reference',type:'relation'}]});const originalRow=await db.save(owner,sourceDB.page.id,null,{id:randomUUID(),schema_revision:1,values:{title:'Template row',relation:child.page.id}});const filled=await collections.instantiate(owner,template.id,{id:randomUUID()});const clonedChildren=(await notes.list(owner,{parent_id:filled.id})).pages;const clonedDB=clonedChildren.find(p=>p.kind==='database');assert.ok(clonedDB);const clonedRows=await db.rows(owner,clonedDB.id);assert.equal(clonedRows.rows.length,1);assert.notEqual(clonedRows.rows[0].id,originalRow.id);assert.equal(clonedRows.rows[0].values.relation.id,clonedChildren.find(p=>p.title==='Child').id);
 const folder=await collections.saveFolder(owner,{title:'Tagged SOPs',filters:{tag:'sop',updated_days:90}});await notes.metadata(owner,id,{expected_revision:meeting.page.revision,tags:['sop']});assert.deepEqual((await collections.folderPages(owner,folder.id,{})).pages.map(p=>p.id),[id]);await assert.rejects(collections.folderPages(bob,folder.id,{}),e=>e.status===404);await assert.rejects(collections.saveFolder(bob,{id:folder.id,title:'Steal',filters:{}}),e=>e.status===404);
 const link=randomUUID();await notes.editBlocks(owner,source.page.id,{client_key:randomUUID(),operations:[{id:link,type:'page_link',position:1,payload:{target_id:id},expected_revision:0}]});assert.equal((await collections.backlinks(owner,id)).pages[0].id,source.page.id);const updated=await notes.get(owner,id);await notes.share(owner,id,{expected_revision:updated.page.revision,members:[{user_id:bob.userId,role:'viewer'}]});assert.equal((await collections.backlinks(bob,id)).pages.length,0);
 const roots=await notes.list(owner,{roots:'true',limit:100});assert.ok(roots.pages.some(p=>p.id===source.page.id));assert.equal(roots.pages.some(p=>p.id===child.page.id),false);
 assert.ok((await collections.related(owner,source.page.id)).pages.some(p=>p.id===child.page.id));
 const treeChild=(await notes.list(owner,{parent_id:source.page.id})).pages.find(p=>p.id===child.page.id);assert.ok(treeChild);
 // A readable child under an inaccessible private ancestor must remain findable,
 // without revealing the ancestor's title or admitting its unrelated children.
 let explicit=await notes.get(owner,child.page.id);explicit=await notes.metadata(owner,child.page.id,{expected_revision:explicit.page.revision,inherit_access:false});await notes.share(owner,child.page.id,{expected_revision:explicit.page.revision,members:[{user_id:bob.userId,role:'viewer'}]});
 assert.equal((await collections.related(bob,child.page.id)).pages.some(p=>p.id===source.page.id),false);
 const bobRoots=await notes.list(bob,{roots:'true',limit:100});assert.ok(bobRoots.pages.some(p=>p.id===child.page.id));assert.equal(bobRoots.pages.some(p=>p.id===source.page.id),false);
 }finally{await f.close();}
});
