import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {createCommsFixture} from './helpers/comms-fixture.js';import {installNotesSchema} from '../notes/schema.js';import {createNotesWorkspace} from '../notes/pages.js';import {createNotesAI} from '../notes/ai.js';
test('AI requires explicit fresh preview and configuration, excludes denied sources and protects generated output after revocation',{timeout:120000},async()=>{
 const f=await createCommsFixture();try{await installNotesSchema(f.pool);const owner=await f.actor('owner');await f.pool.query(`UPDATE employee_permissions SET permission_overrides=permission_overrides||'{"notes.view":true,"notes.ai":true}'::jsonb WHERE user_id=$1`,[f.ids.bob]);const bob=await f.actor('bob'),notes=createNotesWorkspace({pool:f.pool});const page=await notes.create(owner,{id:randomUUID(),title:'Meeting'}),secret=await notes.create(owner,{id:randomUUID(),title:'PRIVATE SOURCE SENTINEL'});
 await notes.editBlocks(owner,page.page.id,{client_key:randomUUID(),operations:[{id:page.blocks[0].id,type:'paragraph',expected_revision:1,payload:{text:'Visible decisions'},position:0},{id:randomUUID(),type:'page_link',expected_revision:0,payload:{target_id:secret.page.id},position:1}]});let current=await notes.get(owner,page.page.id);await notes.share(owner,page.page.id,{expected_revision:current.page.revision,members:[{user_id:bob.userId,role:'editor'}]});
 let calls=0;const env={},ai=createNotesAI({pool:f.pool,env,aiClient:{responses:{create:async input=>{calls++;assert.equal(input.store,false);assert.equal(input.input.includes('PRIVATE SOURCE SENTINEL'),false);return {output_text:'Fixture summary'};}}}});const body={action:'Summarize',page_ids:[page.page.id]};const preview=await ai.review(bob,body);assert.equal(preview.configured,false);assert.equal(JSON.stringify(preview).includes('PRIVATE SOURCE SENTINEL'),false);
 await assert.rejects(ai.run(bob,{...body,preview_hash:preview.preview_hash}),e=>e.status===400);await assert.rejects(ai.run(bob,{...body,preview_hash:preview.preview_hash,confirmed:true}),e=>e.status===503);assert.equal(calls,0);
 env.NOTES_AI_ENABLED='true';env.NOTES_AI_MODEL='fixture';env.OPENAI_API_KEY='fictional-injected-client';await assert.rejects(ai.run(bob,{...body,preview_hash:'stale',confirmed:true}),e=>e.status===409);assert.equal(calls,0);
 const result=await ai.run(bob,{...body,preview_hash:preview.preview_hash,confirmed:true});assert.equal(calls,1);const target=await notes.create(owner,{id:randomUUID(),title:'Output'});const block=randomUUID();await notes.editBlocks(owner,target.page.id,{client_key:randomUUID(),operations:[{id:block,type:'ai_result',payload:{target_id:result.id},expected_revision:0,position:1}]});assert.equal((await notes.get(owner,target.page.id)).blocks.find(b=>b.id===block).text,'Fixture summary');
 current=await notes.get(owner,page.page.id);await notes.share(owner,page.page.id,{expected_revision:current.page.revision,members:[]});await assert.rejects(ai.review(bob,body),e=>e.status===404);assert.equal(calls,1);
 // An output viewer cannot receive the original page's restricted derived text.
 const targetCurrent=await notes.get(owner,target.page.id);await notes.share(owner,target.page.id,{expected_revision:targetCurrent.page.revision,members:[{user_id:bob.userId,role:'viewer'}]});const denied=await notes.get(bob,target.page.id);assert.equal(denied.blocks.find(b=>b.id===block).accessible,false);assert.equal(JSON.stringify(denied).includes('Fixture summary'),false);
 }finally{await f.close();}
});
