import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import express from 'express';
import {createCommsFixture} from './helpers/comms-fixture.js';import {installNotes} from '../notes/index.js';import {installNotesSchema} from '../notes/schema.js';import {createNotesWorkspace} from '../notes/pages.js';import {createNotes} from '../company-comms/notes.js';import {createConversationService} from '../company-comms/messages.js';import {installRateLimits} from '../company-comms/rate-limits.js';import {blockInput} from '../notes/blocks.js';import {inlineTagPattern} from '../notes/search.js';
test('structured blocks whitelist data and validate rich ranges and links',()=>{
 assert.throws(()=>blockInput({id:randomUUID(),type:'html',payload:{html:'<script>'}}));assert.throws(()=>blockInput({id:randomUUID(),type:'paragraph',payload:{text:'a',runs:[{start:0,length:9}]}}));assert.throws(()=>blockInput({id:randomUUID(),type:'webpage',payload:{url:'javascript:alert(1)'}}));
 assert.equal(inlineTagPattern('sales+team'),'(^|[[:space:]])#sales\\+team($|[^[:alnum:]_-])');
 const b=blockInput({id:randomUUID(),type:'contact',payload:{source_id:randomUUID(),customer_name:'secret',context_type:'stage_entry',context_id:'s'}});assert.equal(b.payload.customer_name,undefined);assert.equal(b.payload.context_type,'stage_entry');
});
test('Notes privacy, roles, concurrency, revisions, hierarchy, trash and legacy upgrade',{timeout:120000},async()=>{
 const f=await createCommsFixture();try{
  await installNotesSchema(f.pool);await installNotesSchema(f.pool);
  for(const key of ['alice','bob','carol','admin'])await f.pool.query('UPDATE employee_permissions SET permission_overrides=permission_overrides||$2::jsonb WHERE user_id=$1',[f.ids[key],JSON.stringify({'notes.view':true,'notes.create':true,'notes.share':true,'notes.company':true})]);
  const notes=createNotesWorkspace({pool:f.pool}),actors={};for(const key of ['owner','alice','bob','carol','admin','foreign'])actors[key]=await f.actor(key);
  const create=(who,extra={})=>notes.create(actors[who],{id:randomUUID(),title:'PRIVATE SECRET',...extra});let a=await create('alice');const page=a.page.id,first=a.blocks[0];assert.equal(a.page.access_role,4);
  for(const key of ['owner','admin','bob','foreign']){await assert.rejects(notes.get(actors[key],page),e=>e.status===404);assert.equal((await notes.list(actors[key],{search:'PRIVATE SECRET'})).pages.length,0);}
  await assert.rejects(notes.metadata(actors.alice,page,{expected_revision:1,parent_id:page}),e=>e.status===400);
  const child=await create('alice',{parent_id:page});await assert.rejects(notes.metadata(actors.alice,page,{expected_revision:1,parent_id:child.page.id}),e=>e.status===400);
  a=await notes.share(actors.alice,page,{expected_revision:1,members:[{user_id:f.ids.bob,role:'viewer'},{user_id:f.ids.carol,role:'editor'}]});assert.equal((await notes.get(actors.bob,child.page.id)).page.access_role,1);
  const restrictive=await create('alice',{parent_id:page,inherit_access:false});await assert.rejects(notes.get(actors.bob,restrictive.page.id),e=>e.status===404);
  await assert.rejects(notes.editBlocks(actors.bob,page,{client_key:randomUUID(),operations:[]}),e=>e.status===403);
  const second=randomUUID();a=await notes.editBlocks(actors.alice,page,{client_key:randomUUID(),operations:[{id:second,type:'paragraph',payload:{text:'Second'},position:1,expected_revision:0}]});
  const op={client_key:randomUUID(),operations:[{...first,payload:{text:'Alice text #equipment'},expected_revision:first.revision}]};await notes.editBlocks(actors.alice,page,op);await notes.editBlocks(actors.alice,page,op);
  await notes.editBlocks(actors.carol,page,{client_key:randomUUID(),operations:[{id:second,type:'paragraph',payload:{text:'Carol text'},position:1,expected_revision:1}]});
  await assert.rejects(notes.editBlocks(actors.carol,page,{client_key:randomUUID(),operations:[{...first,payload:{text:'Clobber'},expected_revision:1}]}),e=>e.status===409);
  a=await notes.get(actors.alice,page);assert.deepEqual(a.blocks.map(b=>b.payload.text),['Alice text #equipment','Carol text']);assert.equal((await notes.list(actors.alice,{tag:'equipment'})).pages.length,1);assert.equal((await notes.list(actors.alice,{tag:'equip'})).pages.length,0);const history=await notes.versions(actors.alice,page);assert.ok(history.versions.length>=4);const current=a.page.revision;a=await notes.restore(actors.alice,page,{expected_revision:current,revision:history.versions.at(-1).revision});assert.equal(a.page.revision,current+1);
  a=await notes.share(actors.alice,page,{expected_revision:a.page.revision,members:[]});await assert.rejects(notes.get(actors.bob,page),e=>e.status===404);await assert.rejects(notes.get(actors.bob,child.page.id),e=>e.status===404);
  a=await notes.metadata(actors.alice,page,{expected_revision:a.page.revision,trashed:true});await assert.rejects(notes.get(actors.alice,page),e=>e.status===404);assert.equal((await notes.list(actors.alice,{scope:'trash'})).pages[0].id,page);a=await notes.metadata(actors.alice,page,{expected_revision:a.page.revision,trashed:false});assert.equal(a.page.deleted_at,null);
  const service=createConversationService({pool:f.pool}),room=await service.create(actors.owner,{client_key:randomUUID(),member_ids:[f.ids.alice]});const legacy=createNotes({pool:f.pool});let old=await legacy.save(actors.owner,room.id,null,{title:'Legacy',body:'original',client_key:randomUUID()});let canonical=await notes.get(actors.owner,old.id);assert.equal(canonical.blocks[0].payload.text,'original');old=await legacy.save(actors.owner,null,old.id,{title:'Legacy',body:'old client edit',expected_revision:old.revision});canonical=await notes.get(actors.owner,old.id);assert.equal(canonical.blocks[0].payload.text,'old client edit');
  await notes.editBlocks(actors.owner,old.id,{client_key:randomUUID(),operations:[{...canonical.blocks[0],expected_revision:canonical.blocks[0].revision,payload:{text:'new block edit'}}]});await assert.rejects(legacy.save(actors.owner,null,old.id,{title:'Legacy',body:'unsafe overwrite',expected_revision:old.revision+1}),e=>e.status===409);
  await f.pool.query('UPDATE conversation_participants SET left_at=now() WHERE conversation_id=$1 AND user_id=$2',[room.id,f.ids.alice]);await assert.rejects(notes.get(actors.alice,old.id),e=>e.status===404);
 }finally{await f.close();}
});
test('Notes HTTP auth, Stage ancestry and denied source fields',{timeout:120000},async()=>{
 const f=await createCommsFixture(),app=express();let server;try{
  await installRateLimits(f.pool);app.use(express.json());await installNotes({app,pool:f.pool,authRequired:(req,res,next)=>{if(!f.ids[req.get('X-User')])return res.status(401).json({error:'unauthorized'});req.userId=f.ids[req.get('X-User')];req.companyId=f.companies.a;next();}});server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});
  const req=async(path,who='owner',method='GET',body)=>{const res=await fetch('http://127.0.0.1:'+server.address().port+'/api/notes'+path,{method,headers:{'X-User':who,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});assert.match(res.headers.get('content-type'),/json/);return {status:res.status,body:await res.json()};};
  assert.equal((await req('/capabilities','invalid')).status,401);assert.equal((await req('/capabilities','alice')).status,403);assert.equal((await req('/capabilities')).body.ai_configured,false);
  const note=(await req('/pages','owner','POST',{id:randomUUID(),title:'Sources'})).body;const contact=randomUUID();await f.pool.query('INSERT INTO contacts(id,company_id,name) VALUES($1,$2,$3)',[contact,f.companies.a,'SECRET CUSTOMER']);
  const block={id:randomUUID(),type:'contact',payload:{source_id:contact,context_type:'stage_entry',context_id:'opp'},expected_revision:0,position:1};let result=await req('/pages/'+note.page.id+'/blocks','owner','POST',{client_key:randomUUID(),operations:[block]});assert.equal(result.status,200);assert.equal((await req('/pages?search=SECRET%20CUSTOMER')).body.pages.length,1);
  await f.pool.query(`UPDATE employee_permissions SET permission_overrides=permission_overrides||'{"notes.view":true}'::jsonb WHERE user_id=$1`,[f.ids.bob]);await req('/pages/'+note.page.id+'/members','owner','PUT',{expected_revision:result.body.page.revision,members:[{user_id:f.ids.bob,role:'viewer'}]});result=await req('/pages/'+note.page.id,'bob');assert.equal(result.status,200);assert.equal(JSON.stringify(result.body).includes('SECRET CUSTOMER'),false);assert.equal(result.body.blocks[1].text,'No Access');assert.deepEqual(result.body.blocks[1].payload,{});assert.equal((await req('/pages?search=SECRET%20CUSTOMER','bob')).body.pages.length,0);await f.pool.query(`UPDATE employee_permissions SET permission_overrides=permission_overrides||'{"contacts.view":true,"pipeline.view":false}'::jsonb WHERE user_id=$1`,[f.ids.bob]);assert.equal((await req('/pages?search=SECRET%20CUSTOMER','bob')).body.pages.length,0);
 }finally{if(server)await new Promise(r=>server.close(r));await f.close();}
});
