// Additive and repeatable; messages remain in the canonical conversation engine.
export async function installCallsSchema(db) {
  await db.query(`
 CREATE TABLE IF NOT EXISTS comms_call_settings(company_id uuid PRIMARY KEY REFERENCES companies(id),enabled boolean NOT NULL DEFAULT true,recording_enabled boolean NOT NULL DEFAULT false,guests_enabled boolean NOT NULL DEFAULT false,max_participants integer NOT NULL DEFAULT 12 CHECK(max_participants BETWEEN 2 AND 100),monthly_participant_minutes integer NOT NULL DEFAULT 10000 CHECK(monthly_participant_minutes BETWEEN 0 AND 10000000),max_call_minutes integer NOT NULL DEFAULT 180 CHECK(max_call_minutes BETWEEN 1 AND 1440),version integer NOT NULL DEFAULT 1);
 ALTER TABLE comms_call_settings ADD COLUMN IF NOT EXISTS usage_warning_percent integer NOT NULL DEFAULT 80 CHECK(usage_warning_percent BETWEEN 10 AND 100);
 CREATE TABLE IF NOT EXISTS comms_call_sessions(id uuid PRIMARY KEY,company_id uuid NOT NULL REFERENCES companies(id),conversation_id text NOT NULL REFERENCES conversations(id),creator_user_id uuid NOT NULL REFERENCES users(id),host_user_id uuid NOT NULL REFERENCES users(id),kind text NOT NULL CHECK(kind IN('direct','huddle','meeting')),media text NOT NULL CHECK(media IN('audio','video')),status text NOT NULL DEFAULT 'ringing' CHECK(status IN('ringing','connecting','connected','ended','canceled','declined','missed','failed')),room_name text NOT NULL UNIQUE,meeting_id uuid,pair_key text,locked boolean NOT NULL DEFAULT false,waiting_room boolean NOT NULL DEFAULT false,version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),expires_at timestamptz NOT NULL DEFAULT now()+interval '45 seconds',connected_at timestamptz,ended_at timestamptz,end_reason text,UNIQUE(company_id,id));
 CREATE UNIQUE INDEX IF NOT EXISTS comms_call_live_pair ON comms_call_sessions(company_id,pair_key) WHERE pair_key IS NOT NULL AND ended_at IS NULL;
 CREATE UNIQUE INDEX IF NOT EXISTS comms_call_live_huddle ON comms_call_sessions(company_id,conversation_id) WHERE kind='huddle' AND ended_at IS NULL;
 CREATE INDEX IF NOT EXISTS comms_call_company_created ON comms_call_sessions(company_id,created_at DESC,id);
 CREATE TABLE IF NOT EXISTS comms_call_participants(call_id uuid NOT NULL REFERENCES comms_call_sessions(id),user_id uuid NOT NULL REFERENCES users(id),state text NOT NULL DEFAULT 'invited' CHECK(state IN('invited','accepted','waiting','admitted','joined','left','declined','removed')),device_id uuid,identity text NOT NULL,can_screen_share boolean NOT NULL DEFAULT true,joined_at timestamptz,left_at timestamptz,removed_at timestamptz,recording_consent boolean NOT NULL DEFAULT false,participant_seconds bigint NOT NULL DEFAULT 0,PRIMARY KEY(call_id,user_id),UNIQUE(call_id,identity));
 ALTER TABLE comms_call_participants ADD COLUMN IF NOT EXISTS last_screen_share_allowed boolean;
 ALTER TABLE comms_call_participants ADD COLUMN IF NOT EXISTS hand_raised_at timestamptz;
 ALTER TABLE comms_call_participants ADD COLUMN IF NOT EXISTS reaction text;
 ALTER TABLE comms_call_participants ADD COLUMN IF NOT EXISTS reaction_expires_at timestamptz;
 CREATE TABLE IF NOT EXISTS comms_meetings(id uuid PRIMARY KEY,company_id uuid NOT NULL REFERENCES companies(id),conversation_id text NOT NULL REFERENCES conversations(id),host_user_id uuid NOT NULL REFERENCES users(id),title text NOT NULL,agenda text NOT NULL DEFAULT '',starts_at timestamptz NOT NULL,duration_minutes integer NOT NULL CHECK(duration_minutes BETWEEN 5 AND 1440),timezone text NOT NULL,status text NOT NULL DEFAULT 'scheduled' CHECK(status IN('scheduled','canceled')),waiting_room boolean NOT NULL DEFAULT true,version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now());
 ALTER TABLE comms_meetings ADD COLUMN IF NOT EXISTS source_conversation_id text REFERENCES conversations(id);
 -- Repeatable upgrade: preserve every conversation/message/participant identity.
 UPDATE conversations c SET source_kind=CASE WHEN m.company_id IS DISTINCT FROM c.company_id THEN 'invalid' WHEN m.source_conversation_id IS NULL THEN 'independent' ELSE 'conversation' END,source_id=m.source_conversation_id
 FROM comms_meetings m WHERE m.conversation_id=c.id
 AND c.source_kind IS NULL AND c.source_id IS NULL;
 CREATE UNIQUE INDEX IF NOT EXISTS comms_call_live_meeting ON comms_call_sessions(meeting_id) WHERE meeting_id IS NOT NULL AND ended_at IS NULL;
 CREATE INDEX IF NOT EXISTS comms_meetings_company_start ON comms_meetings(company_id,starts_at,id);
 CREATE TABLE IF NOT EXISTS comms_meeting_attendees(meeting_id uuid NOT NULL REFERENCES comms_meetings(id),user_id uuid NOT NULL REFERENCES users(id),rsvp text NOT NULL DEFAULT 'invited' CHECK(rsvp IN('invited','accepted','declined','tentative')),PRIMARY KEY(meeting_id,user_id));
 CREATE TABLE IF NOT EXISTS comms_call_recordings(id uuid PRIMARY KEY,call_id uuid NOT NULL REFERENCES comms_call_sessions(id),company_id uuid NOT NULL REFERENCES companies(id),requested_by uuid NOT NULL REFERENCES users(id),status text NOT NULL DEFAULT 'consent' CHECK(status IN('consent','starting','recording','stopping','processing','ready','failed')),egress_id text UNIQUE,object_key text NOT NULL,asset_id uuid,media text NOT NULL,byte_size bigint,duration_seconds double precision,error_code text,created_at timestamptz NOT NULL DEFAULT now(),started_at timestamptz,ended_at timestamptz);
 ALTER TABLE comms_call_recordings ADD COLUMN IF NOT EXISTS reconciled_at timestamptz;
 CREATE UNIQUE INDEX IF NOT EXISTS comms_one_active_recording ON comms_call_recordings(call_id) WHERE status IN('consent','starting','recording','stopping','processing');
 CREATE TABLE IF NOT EXISTS comms_call_consents(id bigserial PRIMARY KEY,call_id uuid NOT NULL REFERENCES comms_call_sessions(id),user_id uuid NOT NULL REFERENCES users(id),consented boolean NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
 CREATE TABLE IF NOT EXISTS comms_call_provider_events(id text PRIMARY KEY,event_type text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
 CREATE TABLE IF NOT EXISTS comms_call_jobs(id uuid PRIMARY KEY,call_id uuid REFERENCES comms_call_sessions(id),kind text NOT NULL,payload jsonb NOT NULL DEFAULT '{}',status text NOT NULL DEFAULT 'pending',attempts integer NOT NULL DEFAULT 0,available_at timestamptz NOT NULL DEFAULT now(),last_error text,created_at timestamptz NOT NULL DEFAULT now());
 CREATE INDEX IF NOT EXISTS comms_call_pending_jobs ON comms_call_jobs(available_at) WHERE status='pending';
 CREATE TABLE IF NOT EXISTS comms_call_audit(id bigserial PRIMARY KEY,company_id uuid NOT NULL REFERENCES companies(id),call_id uuid,actor_user_id uuid REFERENCES users(id),action text NOT NULL,target_user_id uuid,created_at timestamptz NOT NULL DEFAULT now());
 CREATE TABLE IF NOT EXISTS comms_voip_devices(user_id uuid NOT NULL REFERENCES users(id),device_id uuid NOT NULL,token text NOT NULL,environment text NOT NULL CHECK(environment IN('sandbox','production')),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(user_id,device_id),UNIQUE(token));
 `);
}
