import {createNotesActivity} from './activity.js';
import {createNotesPreferences} from './preferences.js';
import {createNotesTasks} from './tasks.js';
import {createNotesExports} from './exports.js';
import {createNotesAI} from './ai.js';
import {createNotesCollections} from './collections.js';
import {createNotesDatabases} from './databases.js';
import {searchSources,hydrateSources} from '../company-comms/sources.js';
import {createNotesCollaboration} from './collaboration.js';
import {installNotesSchema} from './schema.js';
import {createNotesWorkspace} from './pages.js';
import {loadActor,requireCapability} from '../company-comms/access.js';
import {takeRateLimit} from '../company-comms/rate-limits.js';
export async function installNotes({app,pool,authRequired,notifications,env=process.env,aiClient,storage}){
 await installNotesSchema(pool);const notes=createNotesWorkspace({pool,notifications}),collaboration=createNotesCollaboration({pool,notifications}),databases=createNotesDatabases({pool,notes}),collections=createNotesCollections({pool,notes}),ai=createNotesAI({pool,env,aiClient}),exports=createNotesExports({pool,storage}),tasks=createNotesTasks({pool,notes,notifications}),preferences=createNotesPreferences({pool}),activity=createNotesActivity({pool});
 const route=(method,path,fn)=>app[method]('/api/notes'+path,authRequired,async(req,res)=>{res.set('Cache-Control','private, no-store');try{await takeRateLimit(pool,req,path==='/ai'?{bucket:'notes_ai',limit:5}:undefined);res.json(await fn(req));}catch(e){res.status(e.status||503).json({error:e.status?(e.code||e.message):'notes_unavailable',message:e.status?e.message:'Notes is temporarily unavailable. Your local changes are preserved.'});}});
 route('get','/capabilities',async r=>{const actor=await loadActor(pool,r);requireCapability(actor,'notes.view');return {version:1,blocks:true,ai_configured:ai.configured()};});
 route('get','/sources/search',async r=>{const actor=await loadActor(pool,r);requireCapability(actor,'notes.view');return {items:await searchSources(pool,actor,r.query.type,r.query.search||'')};});
 route('post','/sources/resolve',async r=>{const actor=await loadActor(pool,r);requireCapability(actor,'notes.view');return (await hydrateSources(pool,actor,[{...r.body,id:'note-source'}])).get('note-source');});
 route('get','/pages',r=>notes.list(r,r.query));route('post','/pages',r=>notes.create(r,r.body));
 route('get','/pages/:id',r=>notes.get(r,r.params.id,r.query));route('patch','/pages/:id',r=>notes.metadata(r,r.params.id,r.body));
 route('post','/pages/:id/blocks',r=>notes.editBlocks(r,r.params.id,r.body));route('put','/pages/:id/personal',r=>notes.personal(r,r.params.id,r.body));
 route('get','/pages/:id/members',r=>notes.members(r,r.params.id));route('put','/pages/:id/members',r=>notes.share(r,r.params.id,r.body));
 route('get','/pages/:id/versions',r=>notes.versions(r,r.params.id));route('get','/pages/:id/versions/:revision',r=>notes.version(r,r.params.id,Number(r.params.revision)));route('post','/pages/:id/restore',r=>notes.restore(r,r.params.id,r.body));
 route('get','/pages/:id/blocks/:block',r=>notes.getBlock(r,r.params.id,r.params.block));
 route('get','/pages/:id/people',r=>collaboration.pagePeople(r,r.params.id));
 route('get','/people',r=>collaboration.people(r,r.query.search||''));
 route('get','/pages/:id/comments',r=>collaboration.list(r,r.params.id,r.query));route('post','/pages/:id/comments',r=>collaboration.save(r,r.params.id,null,r.body));route('patch','/pages/:id/comments/:comment',r=>collaboration.save(r,r.params.id,r.params.comment,r.body));route('put','/pages/:id/presence',r=>collaboration.presence(r,r.params.id,r.body));
 route('get','/pages/:id/activity',r=>activity.list(r,r.params.id,r.query));
 route('get','/preferences',r=>preferences.get(r));route('put','/preferences',r=>preferences.save(r,r.body));
 route('get','/pages/:id/database',r=>databases.get(r,r.params.id));route('put','/pages/:id/database',r=>databases.configure(r,r.params.id,r.body));route('get','/pages/:id/rows',r=>databases.rows(r,r.params.id,r.query));route('post','/pages/:id/rows',r=>databases.save(r,r.params.id,null,r.body));route('get','/pages/:id/rows/:row',r=>databases.getRow(r,r.params.id,r.params.row));route('patch','/pages/:id/rows/:row',r=>databases.save(r,r.params.id,r.params.row,r.body));
 route('get','/smart-folders',r=>collections.folders(r));route('post','/smart-folders',r=>collections.saveFolder(r,r.body));route('get','/smart-folders/:id/pages',r=>collections.folderPages(r,r.params.id,r.query));
 route('get','/templates',r=>collections.templates(r));route('post','/templates',r=>collections.saveTemplate(r,r.body));route('post','/templates/:id/create',r=>collections.instantiate(r,r.params.id,r.body));route('get','/pages/:id/related',r=>collections.related(r,r.params.id));route('get','/pages/:id/backlinks',r=>collections.backlinks(r,r.params.id));
 route('post','/ai/preview',r=>ai.review(r,r.body));route('post','/ai',r=>ai.run(r,r.body));
 route('get','/pages/:id/export',r=>exports.context(r,r.params.id,r.query.mode));route('post','/pages/:id/exports',r=>exports.reserve(r,r.params.id,r.body));
 route('post','/pages/:id/purge',r=>notes.purge(r,r.params.id,r.body));
 route('post','/pages/:id/blocks/:block/task',r=>tasks.convert(r,r.params.id,r.params.block,r.body));
 return notes;
}
