import {createWorkflows} from './workflows.js';
import {randomUUID} from 'node:crypto';
import {createNotes} from './notes.js';
import {createPolls} from './polls.js';
import {createScheduled} from './scheduled.js';
import {createCommsSearch} from './search.js';
import {createTaskInTransaction,taskAccessSQL} from './tasks.js';
import {authorizeConversation,loadActor,mutate,requireCapability,fail,id,uuid,can,conversationJoins,conversationAccessSQL} from './access.js';
import {storagePredicate} from './assets.js';
import {publicFile} from '../media-storage/domain.js';
import {takeRateLimit} from './rate-limits.js';
const TEMPLATES=Object.freeze([
 {id:'announcement',title:'Team announcement',body:'## Update\n\nWhat changed:\n\nWho is affected:\n\nNext steps:'},
 {id:'daily-plan',title:'Daily plan',body:'## Today\n\n- [ ] Priority one\n- [ ] Priority two\n\nBlockers:\n\nEnd-of-day handoff:'},
 {id:'handoff',title:'Job handoff',body:'## Handoff\n\nWork completed:\n\nRemaining work:\n\n- [ ] Equipment returned\n- [ ] Customer follow-up assigned'},
 {id:'equipment',title:'Equipment issue',body:'## Equipment issue\n\nEquipment:\n\nObserved problem:\n\nCurrent location:\n\nSafety / service impact:'},
 {id:'agenda',title:'Meeting agenda',body:'## Agenda\n\nGoal:\n\nTopics:\n\nDecisions:\n\n- [ ] Assign follow-ups'}
]);
export function installCollaboration({app,pool,authRequired,messages,notifications,emitAutomationEvent=async()=>null,startWorker=true}){
 const notes=createNotes({pool}),polls=createPolls({pool,messages}),scheduled=createScheduled({pool,messages}),search=createCommsSearch({pool}),workflows=createWorkflows({pool,messages,notifications});
 const route=(method,path,fn)=>app[method]('/api/comms'+path,authRequired,async(req,res)=>{res.set('Cache-Control','private, no-store');try{await takeRateLimit(pool,req);res.json(await fn(req));}catch(error){if(!error.status)console.error('[comms_collaboration]',{path,code:error.code||error.name});res.status(error.status||503).json({error:error.status?error.code:'collaboration_unavailable',message:error.status?error.message:'Collaboration is temporarily unavailable.'});}});
 route('get','/conversations/:id/workflows',async r=>({workflows:await workflows.list(r,r.params.id)}));route('post','/conversations/:id/workflows',r=>workflows.save(r,r.params.id,null,r.body));route('patch','/workflows/:id',r=>workflows.save(r,null,r.params.id,r.body));route('post','/workflows/:id/submit',r=>workflows.submit(r,r.params.id,r.body));route('get','/workflows/:id/runs',async r=>({runs:await workflows.history(r,r.params.id)}));route('get','/workflow-runs/:id',r=>workflows.getRun(r,r.params.id));route('post','/workflow-runs/:id/decision',r=>workflows.decide(r,r.params.id,r.body));
 route('get','/templates',async r=>{const actor=await loadActor(pool,r);requireCapability(actor,'communications.view');return {templates:TEMPLATES};});
 route('get','/conversations/:id/notes',async r=>({notes:await notes.list(r,r.params.id)}));route('post','/conversations/:id/notes',r=>notes.save(r,r.params.id,null,r.body));route('get','/notes/:id',r=>notes.get(r,r.params.id));route('patch','/notes/:id',r=>notes.save(r,null,r.params.id,r.body));route('delete','/notes/:id',r=>notes.remove(r,r.params.id,r.body));route('get','/notes/:id/versions',async r=>({versions:await notes.versions(r,r.params.id)}));
 route('post','/conversations/:id/polls',r=>polls.create(r,r.params.id,r.body));route('get','/polls/:id',r=>polls.get(r,r.params.id));route('put','/polls/:id/vote',r=>polls.vote(r,r.params.id,r.body));route('post','/polls/:id/close',r=>polls.close(r,r.params.id));
 route('get','/conversations/:id/scheduled',async r=>({scheduled:await scheduled.list(r,r.params.id)}));route('post','/conversations/:id/scheduled',r=>scheduled.save(r,r.params.id,null,r.body));route('patch','/scheduled/:id',r=>scheduled.save(r,null,r.params.id,r.body));route('delete','/scheduled/:id',r=>scheduled.cancel(r,r.params.id,r.body));
 route('post','/messages/:id/task',r=>mutate(pool,r,(db,actor)=>createTaskInTransaction(db,actor,r.params.id,r.body)));
 route('get','/conversations/:id/tasks',async r=>{const c=await authorizeConversation(pool,r,r.params.id),actor=c.actor;requireCapability(actor,'tasks.view');return {tasks:(await pool.query(`SELECT t.*,true AS comms_protected,l.source_type,l.source_id,l.conversation_id FROM comms_task_links l JOIN todo_tasks t ON t.id=l.task_id WHERE l.conversation_id=$3 AND l.company_id=$2 AND ${taskAccessSQL(actor,'t')} ORDER BY t.due_date NULLS LAST,t.updated_at DESC LIMIT 100`,[actor.userId,actor.companyId,c.id])).rows};});
 route('get','/search',r=>search.search(r,r.query));
 route('put','/saved/items',r=>mutate(pool,r,async(db,actor)=>{const type=r.body.subject_type,subject=id(r.body.subject_id);if(type==='note'){await notes.get(actor,subject);}else if(type==='file'){const acl=await storagePredicate(db,actor);if(!(await db.query(`SELECT 1 FROM stored_files f WHERE f.id=$3 AND f.cloud_status='active' AND (${acl})`,[actor.userId,actor.companyId,uuid(subject)])).rowCount)fail(404,'file_unavailable');await db.query(`INSERT INTO storage_file_state(user_id,file_id,favorite) VALUES($1,$2,$3) ON CONFLICT(user_id,file_id) DO UPDATE SET favorite=$3,updated_at=now()`,[actor.userId,subject,r.body.saved===true]);}else fail(400,'invalid_saved_type');if(r.body.saved===false)await db.query('DELETE FROM comms_saved_items WHERE user_id=$1 AND subject_type=$2 AND subject_id=$3',[actor.userId,type,subject]);else await db.query('INSERT INTO comms_saved_items(user_id,company_id,subject_type,subject_id) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING',[actor.userId,actor.companyId,type,subject]);return {ok:true};}));
 async function saved(input){const actor=await loadActor(pool,input);requireCapability(actor,'communications.view');const result=[];for(const message of await messages.saved(actor))result.push({type:'message',id:message.id,conversation_id:message.conversation_id,title:message.body,created_at:message.created_at,data:message});
  const noteRows=(await pool.query(`SELECT n.* FROM comms_saved_items si JOIN comms_notes n ON n.id::text=si.subject_id JOIN conversations c ON c.id=n.conversation_id ${conversationJoins} WHERE si.user_id=$1 AND si.subject_type='note' AND n.deleted_at IS NULL AND ${conversationAccessSQL(actor)} ORDER BY si.created_at DESC LIMIT 100`,[actor.userId,actor.companyId])).rows;for(const note of noteRows)result.push({type:'note',id:note.id,conversation_id:note.conversation_id,title:note.title,created_at:note.created_at,data:await notes.hydrate(pool,actor,note)});
  const acl=await storagePredicate(pool,actor),files=(await pool.query(`SELECT f.* FROM storage_file_state s JOIN stored_files f ON f.id=s.file_id WHERE s.user_id=$1 AND s.favorite AND f.cloud_status='active' AND (${acl}) ORDER BY s.updated_at DESC LIMIT 100`,[actor.userId,actor.companyId])).rows;for(const file of files)result.push({type:'file',id:file.id,title:file.display_name,created_at:file.created_at,data:publicFile(file,actor)});
  const reminders=(await pool.query(`SELECT m.id,m.conversation_id,m.body,p.remind_at FROM comms_message_personal p JOIN messages m ON m.id=p.message_id JOIN conversations c ON c.id=COALESCE(m.conversation_id,(SELECT lt.conversation_id FROM comms_threads lt WHERE lt.legacy_channel_id=m.channel_id)) ${conversationJoins} WHERE p.user_id=$1 AND p.remind_at IS NOT NULL AND m.deleted_at IS NULL AND ${conversationAccessSQL(actor)} ORDER BY p.remind_at LIMIT 100`,[actor.userId,actor.companyId])).rows;for(const reminder of reminders)result.push({type:'reminder',id:reminder.id,conversation_id:reminder.conversation_id,title:reminder.body,created_at:reminder.remind_at,data:{remind_at:reminder.remind_at}});return {items:result.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,200)};
 }
 route('get','/saved/all',r=>saved(r));
 async function reminders(){const rows=(await pool.query(`SELECT p.message_id,p.user_id,p.remind_at::text AS precise_remind_at,m.company_id FROM comms_message_personal p JOIN messages m ON m.id=p.message_id WHERE p.remind_at<=now() ORDER BY p.remind_at LIMIT 20`)).rows;for(const row of rows){const db=await pool.connect();try{await db.query('BEGIN');await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['comms-permissions:'+row.user_id]);const current=(await db.query('SELECT remind_at::text AS remind_at FROM comms_message_personal WHERE message_id=$1 AND user_id=$2 FOR UPDATE',[row.message_id,row.user_id])).rows[0];if(current?.remind_at!==row.precise_remind_at){await db.query('COMMIT');continue;}await db.query('SAVEPOINT reminder_access');try{const actor=await loadActor(db,{userId:row.user_id,companyId:row.company_id});const m=await messages.message(db,actor,row.message_id);if(m.deleted_at)fail(404,'message_unavailable');await notifications.enqueue(db,{userId:actor.userId,companyId:actor.companyId,kind:'comms.reminder',title:'Saved message reminder',body:'Your personal message reminder is ready.',conversationId:m.canonical_conversation_id,eventKey:row.message_id+':'+row.precise_remind_at,requirements:['communications.view']});}catch(e){await db.query('ROLLBACK TO SAVEPOINT reminder_access');if(!e.status)throw e;}await db.query('UPDATE comms_message_personal SET remind_at=NULL WHERE message_id=$1 AND user_id=$2',[row.message_id,row.user_id]);await db.query('COMMIT');}catch(e){await db.query('ROLLBACK');throw e;}finally{db.release();}}}
 async function dispatchEvents(){const pending=(await pool.query('SELECT * FROM comms_automation_outbox WHERE delivered_at IS NULL ORDER BY created_at LIMIT 20')).rows;for(const event of pending){try{const actor=await loadActor(pool,{userId:event.actor_id,companyId:event.company_id});if(event.subject_type==='task'){requireCapability(actor,'tasks.view');const visible=await pool.query(`SELECT 1 FROM todo_tasks t WHERE t.id=$3 AND ${taskAccessSQL(actor,'t')}`,[actor.userId,actor.companyId,event.subject_id]);if(!visible.rowCount)fail(404,'task_unavailable');}else {requireCapability(actor,'communications.workflows');const workflow=(await pool.query('SELECT conversation_id FROM comms_workflows WHERE id=$1 AND company_id=$2 AND deleted_at IS NULL',[event.subject_id,actor.companyId])).rows[0];if(!workflow)fail(404,'workflow_unavailable');await authorizeConversation(pool,actor,workflow.conversation_id);}}catch(error){if(!error.status)throw error;await pool.query('UPDATE comms_automation_outbox SET delivered_at=now() WHERE id=$1',[event.id]);continue;}const emitted=await emitAutomationEvent({companyId:event.company_id,actorUserId:event.actor_id,eventType:event.event_type,subjectType:event.subject_type,subjectId:event.subject_id,source:'company_comms',dedupeKey:'comms:'+event.id,payload:event.payload});if(emitted)await pool.query('UPDATE comms_automation_outbox SET delivered_at=now() WHERE id=$1',[event.id]);}}
 let running=false;const tick=async()=>{if(running)return;running=true;try{await scheduled.tick();await reminders();await workflows.tick();await dispatchEvents();}finally{running=false;}};const timer=startWorker?setInterval(()=>tick().catch(e=>console.error('[comms_collaboration] worker',{code:e.code||e.name})),5000):null;timer?.unref();return {notes,polls,scheduled,search,workflows,saved,tick,stop:()=>clearInterval(timer)};
}
