export async function installCollaborationSchema(db){await db.query(`
 CREATE TABLE IF NOT EXISTS comms_notes(id uuid PRIMARY KEY,company_id uuid NOT NULL REFERENCES companies(id),conversation_id text NOT NULL REFERENCES conversations(id),creator_id uuid NOT NULL REFERENCES users(id),editor_id uuid NOT NULL REFERENCES users(id),client_key text NOT NULL,title text NOT NULL,body text NOT NULL DEFAULT '',asset_ids jsonb NOT NULL DEFAULT '[]',source_refs jsonb NOT NULL DEFAULT '[]',revision integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,UNIQUE(company_id,creator_id,client_key));
 CREATE INDEX IF NOT EXISTS comms_notes_conversation ON comms_notes(conversation_id,updated_at DESC) WHERE deleted_at IS NULL;
 CREATE INDEX IF NOT EXISTS comms_notes_search ON comms_notes USING gin(to_tsvector('simple',title||' '||body)) WHERE deleted_at IS NULL;
 CREATE TABLE IF NOT EXISTS comms_note_versions(note_id uuid NOT NULL REFERENCES comms_notes(id),revision integer NOT NULL,title text NOT NULL,body text NOT NULL,asset_ids jsonb NOT NULL,source_refs jsonb NOT NULL,editor_id uuid NOT NULL REFERENCES users(id),created_at timestamptz NOT NULL,PRIMARY KEY(note_id,revision));
 CREATE TABLE IF NOT EXISTS comms_polls(message_id text PRIMARY KEY REFERENCES messages(id),company_id uuid NOT NULL REFERENCES companies(id),author_id uuid NOT NULL REFERENCES users(id),multiple boolean NOT NULL DEFAULT false,closes_at timestamptz,closed_at timestamptz,revision integer NOT NULL DEFAULT 1);
 CREATE TABLE IF NOT EXISTS comms_poll_options(id uuid PRIMARY KEY,poll_id text NOT NULL REFERENCES comms_polls(message_id),label text NOT NULL,sort_order integer NOT NULL,UNIQUE(poll_id,sort_order));
 CREATE TABLE IF NOT EXISTS comms_poll_votes(poll_id text NOT NULL REFERENCES comms_polls(message_id),option_id uuid NOT NULL REFERENCES comms_poll_options(id),user_id uuid NOT NULL REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(poll_id,option_id,user_id));
 CREATE TABLE IF NOT EXISTS comms_scheduled_messages(id uuid PRIMARY KEY,company_id uuid NOT NULL REFERENCES companies(id),conversation_id text NOT NULL REFERENCES conversations(id),sender_id uuid NOT NULL REFERENCES users(id),client_key text NOT NULL,payload jsonb NOT NULL,send_at timestamptz NOT NULL,timezone text NOT NULL DEFAULT 'UTC',status text NOT NULL DEFAULT 'scheduled' CHECK(status IN('scheduled','sent','canceled','failed')),revision integer NOT NULL DEFAULT 1,message_id text REFERENCES messages(id),error_code text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(company_id,sender_id,client_key));
 CREATE INDEX IF NOT EXISTS comms_scheduled_due ON comms_scheduled_messages(send_at,id) WHERE status='scheduled';
 CREATE TABLE IF NOT EXISTS comms_task_links(task_id text PRIMARY KEY REFERENCES todo_tasks(id) ON DELETE CASCADE,company_id uuid NOT NULL REFERENCES companies(id),conversation_id text NOT NULL REFERENCES conversations(id),source_type text NOT NULL,source_id text NOT NULL,source_refs jsonb NOT NULL DEFAULT '[]',requirements jsonb NOT NULL DEFAULT '[]',created_by uuid NOT NULL REFERENCES users(id),client_key text NOT NULL,revoked_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(company_id,created_by,client_key));
 ALTER TABLE comms_task_links ADD COLUMN IF NOT EXISTS source_dependencies jsonb NOT NULL DEFAULT '[]';
 DO $task_log$ BEGIN IF to_regclass('todo_logs') IS NOT NULL THEN
  ALTER TABLE todo_logs ADD COLUMN IF NOT EXISTS comms_protected boolean NOT NULL DEFAULT false;
  UPDATE todo_logs l SET comms_protected=true WHERE NOT l.comms_protected AND EXISTS(SELECT 1 FROM comms_task_links cl WHERE cl.task_id=l.task_id);
 END IF; END $task_log$;
 CREATE OR REPLACE FUNCTION comms_recording_task_ready(source_id text) RETURNS boolean LANGUAGE plpgsql STABLE AS $fn$
 DECLARE ready boolean;
 BEGIN
  IF to_regclass('comms_review_actions') IS NULL OR to_regclass('comms_processing_jobs') IS NULL OR to_regclass('comms_call_recordings') IS NULL THEN RETURN false; END IF;
  EXECUTE 'SELECT EXISTS(SELECT 1 FROM comms_review_actions a JOIN comms_processing_jobs j ON j.id=a.job_id JOIN comms_call_recordings r ON r.id=j.recording_id JOIN stored_files f ON f.id=r.asset_id WHERE a.id::text=$1 AND a.state=''approved'' AND j.status=''ready'' AND r.status=''ready'' AND f.cloud_status=''active'' AND f.deleted_at IS NULL)' INTO ready USING source_id;
  RETURN ready;
 END $fn$;
 CREATE TABLE IF NOT EXISTS comms_saved_items(user_id uuid NOT NULL REFERENCES users(id),company_id uuid NOT NULL REFERENCES companies(id),subject_type text NOT NULL CHECK(subject_type IN('note','file')),subject_id text NOT NULL,remind_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(user_id,subject_type,subject_id));
 CREATE TABLE IF NOT EXISTS comms_workflows(id uuid PRIMARY KEY,company_id uuid NOT NULL REFERENCES companies(id),conversation_id text NOT NULL REFERENCES conversations(id),creator_id uuid NOT NULL REFERENCES users(id),name text NOT NULL,definition jsonb NOT NULL,enabled boolean NOT NULL DEFAULT false,revision integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz);
 CREATE TABLE IF NOT EXISTS comms_workflow_runs(id uuid PRIMARY KEY,workflow_id uuid NOT NULL REFERENCES comms_workflows(id),company_id uuid NOT NULL REFERENCES companies(id),requester_id uuid NOT NULL REFERENCES users(id),client_key text NOT NULL,definition_revision integer NOT NULL,fields jsonb NOT NULL,asset_ids jsonb NOT NULL DEFAULT '[]',source_refs jsonb NOT NULL DEFAULT '[]',assignee_ids jsonb NOT NULL DEFAULT '[]',state text NOT NULL CHECK(state IN('pending','approved','rejected','skipped','failed')),revision integer NOT NULL DEFAULT 1,result jsonb NOT NULL DEFAULT '[]',error_code text,reviewer_id uuid REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),reviewed_at timestamptz,UNIQUE(workflow_id,requester_id,client_key));
 CREATE INDEX IF NOT EXISTS comms_workflow_run_history ON comms_workflow_runs(workflow_id,created_at DESC,id);
 CREATE TABLE IF NOT EXISTS comms_workflow_reminders(id uuid PRIMARY KEY,run_id uuid NOT NULL REFERENCES comms_workflow_runs(id),company_id uuid NOT NULL REFERENCES companies(id),conversation_id text NOT NULL REFERENCES conversations(id),requester_id uuid NOT NULL REFERENCES users(id),recipient_id uuid NOT NULL REFERENCES users(id),source_refs jsonb NOT NULL DEFAULT '[]',due_at timestamptz NOT NULL,delivered_at timestamptz,canceled_at timestamptz);
 CREATE INDEX IF NOT EXISTS comms_workflow_reminder_due ON comms_workflow_reminders(due_at) WHERE delivered_at IS NULL AND canceled_at IS NULL;
 CREATE TABLE IF NOT EXISTS comms_automation_outbox(id uuid PRIMARY KEY,company_id uuid NOT NULL REFERENCES companies(id),actor_id uuid NOT NULL REFERENCES users(id),event_type text NOT NULL,subject_type text NOT NULL,subject_id text NOT NULL,payload jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),delivered_at timestamptz);
 `);}
