import {installRateLimits,takeRateLimit} from './rate-limits.js';
import {installCollaborationSchema} from './collaboration-schema.js';
import {installLegacyAssets} from './legacy-assets.js';
import {randomUUID} from 'node:crypto';
import {installCommsSchema,installAssetGrants} from './schema.js';
import {createGroupService} from './groups.js';
import {createConversationService} from './messages.js';
import {installNotificationsSchema,createNotifications} from './notifications.js';
import {hydrateSources,searchSources,validateShares} from './sources.js';
import {storagePredicate} from './assets.js';
import {publicFile} from '../media-storage/domain.js';
import {authorizeConversation,loadActor,can,requireCapability,conversationJoins,conversationAccessSQL,mutate,id,uuid,text,fail,publish} from './access.js';
export async function installCompanyComms({app,pool,authRequired,sendPush,startWorker=true}){
 await installRateLimits(pool);await installCommsSchema(pool);await installAssetGrants(pool);await installCollaborationSchema(pool);await installLegacyAssets(pool);await installNotificationsSchema(pool);
 const notifications=createNotifications({pool,sendPush});const groups=createGroupService({pool}),messages=createConversationService({pool,notify:notifications.notify});
 const route=(method,path,fn)=>app[method]('/api/comms'+path,authRequired,async(req,res)=>{res.set('Cache-Control','private, no-store');try{await takeRateLimit(pool,req);res.json(await fn(req));}catch(e){if(!e.status)console.error('[company_comms]',{route:path,code:e.code||e.name});res.status(e.status||503).json({error:e.status?e.code:'comms_unavailable',message:e.status?e.message:'Company Comms is temporarily unavailable. Please retry.'});}});
 route('get','/bootstrap',async r=>{const actor=await loadActor(pool,r);requireCapability(actor,'communications.view');const [g,c]=await Promise.all([groups.list(actor),messages.list(actor)]);return {version:1,groups:g,conversations:c,capabilities:actor.permissions.capabilities,calls:{configured:!!app.locals.commsCalls?.configured}};});
 route('get','/groups',async r=>({groups:await groups.list(r,{directory:r.query.directory==='true'})}));route('post','/groups',r=>groups.create(r,r.body));route('get','/groups/governance',async r=>({groups:await groups.governanceList(r)}));route('get','/groups/:id',r=>groups.detail(r,r.params.id));route('patch','/groups/:id',r=>groups.update(r,r.params.id,r.body));
 route('post','/groups/:id/membership',r=>groups.membership(r,r.params.id,r.body));route('post','/groups/:id/lifecycle',r=>groups.lifecycle(r,r.params.id,r.body));route('post','/groups/:id/governance',r=>groups.governance(r,r.params.id,r.body));
 for(const type of ['section','thread']){route('post',`/groups/:id/${type}s`,r=>groups.structure(r,r.params.id,type,null,r.body));route('patch',`/groups/:id/${type}s/:entity`,r=>groups.structure(r,r.params.id,type,r.params.entity,r.body));route('post',`/groups/:id/${type}s/:entity/lifecycle`,r=>groups.structureLifecycle(r,r.params.id,type,r.params.entity,r.body));}
 route('put','/preferences',r=>groups.preferences(r,r.body));
 route('get','/conversations',async r=>{let conversations=await messages.list(r);if(r.query.writable==='true'){const visible=[];for(const c of conversations)try{await authorizeConversation(pool,r,c.id,{write:true});visible.push(c);}catch(e){if(!e.status)throw e;}conversations=visible;}return {conversations};});
 route('post','/conversations',r=>messages.create(r,r.body));
 route('patch','/conversations/:id',r=>mutate(pool,r,async(db,actor)=>{await db.query('SELECT id FROM conversations WHERE id=$1 FOR UPDATE',[id(r.params.id)]);const c=await authorizeConversation(db,actor,r.params.id,{write:true});if(c.thread_id||!['dm','group_dm'].includes(c.scope))fail(400,'use_channel_controls');if(c.created_by!==actor.userId)fail(403,'conversation_creator_required');if(r.body.expected_revision!==c.revision)fail(409,'stale_revision');
  let photo=c.photo_asset_id;if(Object.hasOwn(r.body,'photo_asset_id')){photo=r.body.photo_asset_id?uuid(r.body.photo_asset_id):null;if(photo){requireCapability(actor,'storage.share');requireCapability(actor,'communications.share');if(!(await db.query("SELECT 1 FROM stored_files WHERE id=$1 AND owner_user_id=$2 AND company_id=$3 AND cloud_status='active' AND category='image'",[photo,actor.userId,actor.companyId])).rowCount)fail(404,'photo_unavailable');}
   await db.query("UPDATE comms_asset_grants SET revoked_at=now() WHERE conversation_id=$1 AND source_type='conversation_photo' AND revoked_at IS NULL",[c.id]);if(photo)await db.query("INSERT INTO comms_asset_grants(asset_id,conversation_id,company_id,granted_by,source_type,source_id) VALUES($1,$2,$3,$4,'conversation_photo',$2) ON CONFLICT(asset_id,conversation_id,source_type,source_id) DO UPDATE SET revoked_at=NULL",[photo,c.id,actor.companyId,actor.userId]);}
  const saved=(await db.query('UPDATE conversations SET title=$2,photo_asset_id=$3,revision=revision+1,updated_at=now() WHERE id=$1 RETURNING *',[c.id,r.body.title===undefined?c.title:text(r.body.title,100),photo])).rows[0];await publish(db,actor,c.id,'conversation.updated',c.id);return {...saved,participants:await messages.participants(db,actor,c.id)};
 }));route('get','/conversations/:id/participants',async r=>{const c=await authorizeConversation(pool,r,r.params.id);return {members:await messages.participants(pool,c.actor,c.id),mention_scopes:messages.mentionScopes(c.actor,c),conversation_scope:c.scope};});route('get','/conversations/:id/messages',r=>messages.history(r,r.params.id,r.query));route('post','/conversations/:id/messages',r=>messages.send(r,r.params.id,r.body));
 route('get','/conversations/:id/unread-target',async r=>{const c=await authorizeConversation(pool,r,r.params.id);const row=(await pool.query(`SELECT m.id,m.created_at,m.reply_root_id FROM messages m LEFT JOIN conversation_participants cp ON cp.conversation_id=$1 AND cp.user_id=$2 WHERE (m.conversation_id=$1 OR m.channel_id=$3) AND m.sender_id<>$2 AND m.deleted_at IS NULL AND m.created_at>COALESCE(cp.last_read_at,'-infinity') AND m.created_at>=COALESCE(cp.history_from,'-infinity') ORDER BY m.created_at,m.id LIMIT 1`,[c.id,c.actor.userId,c.legacy_channel_id])).rows[0];return {message:row||null};});
 route('get','/messages/:id/reply-participants',r=>messages.replyParticipants(r,r.params.id,r.query));
 route('get','/messages/:id',async r=>{const actor=await loadActor(pool,r),{conversation,...row}=await messages.message(pool,actor,r.params.id);return (await messages.hydrate(pool,conversation.actor,[{...row,conversation_id:row.canonical_conversation_id}]))[0];});
 route('patch','/messages/:id',r=>messages.edit(r,r.params.id,r.body));route('delete','/messages/:id',r=>messages.edit(r,r.params.id,r.body,true));route('put','/messages/:id/reaction',r=>messages.reaction(r,r.params.id,r.body));
 route('post','/conversations/:id/read',r=>messages.read(r,r.params.id,r.body));route('post','/conversations/:id/unread',r=>messages.read(r,r.params.id,r.body,true));route('put','/messages/:id/personal',r=>messages.personal(r,r.params.id,r.body));route('put','/messages/:id/pin',r=>messages.pin(r,r.params.id,r.body));route('get','/saved',async r=>({messages:await messages.saved(r)}));
 route('post','/conversations/:id/members',r=>messages.members(r,r.params.id,r.body));route('post','/messages/:id/forward',r=>messages.forward(r,r.params.id,r.body));
 route('get','/members',async r=>{const actor=await loadActor(pool,r);requireCapability(actor,'communications.view');const rows=(await pool.query(`SELECT u.id,u.display_name,u.photo_url FROM users u WHERE u.company_id=$1 AND u.deleted_at IS NULL AND COALESCE(u.display_name,'') ILIKE $2 ORDER BY u.display_name,u.id LIMIT 100`,[actor.companyId,'%'+text(r.query.search||'',100,false).replace(/[\\%_]/g,'\\$&')+'%'])).rows;const members=[];for(const row of rows)if(can(await loadActor(pool,{userId:row.id,companyId:actor.companyId}),'communications.view'))members.push(row);return {members};});
 route('get','/sources/search',async r=>({items:await searchSources(pool,r,r.query.type,r.query.search||'')}));
 route('post','/sources/resolve',async r=>{const actor=await loadActor(pool,r);requireCapability(actor,'communications.view');const refs=[{source_type:text(r.body.source_type,40),source_id:id(r.body.source_id),context_type:r.body.context_type||r.body.source_type,context_id:r.body.context_id||null,id:'selected'}];return (await hydrateSources(pool,actor,refs)).get('selected');});
 route('get','/conversations/:id/assets/:asset',async r=>{const c=await authorizeConversation(pool,r,r.params.id);const actor=c.actor,acl=await storagePredicate(pool,actor);const file=(await pool.query(`SELECT f.* FROM stored_files f WHERE f.id=$3 AND f.cloud_status='active' AND (${acl}) AND (EXISTS(SELECT 1 FROM comms_asset_refs ar JOIN messages m ON m.id=ar.message_id WHERE ar.asset_id=f.id AND (m.conversation_id=$4 OR m.channel_id IN (SELECT legacy_channel_id FROM comms_threads WHERE conversation_id=$4)) AND m.deleted_at IS NULL) OR EXISTS(SELECT 1 FROM comms_asset_grants gr WHERE gr.asset_id=f.id AND gr.conversation_id=$4 AND gr.revoked_at IS NULL))`,[actor.userId,actor.companyId,uuid(r.params.asset),c.id])).rows[0];if(!file)fail(404,'attachment_unavailable');return publicFile(file,actor);});
 route('get','/notifications',r=>notifications.list(r,r.query));route('get','/notifications/preferences',async r=>{const actor=await loadActor(pool,r);requireCapability(actor,'notifications.view');return (await pool.query('SELECT muted,quiet_start,quiet_end,timezone FROM notification_preferences WHERE user_id=$1',[actor.userId])).rows[0]||{muted:false,quiet_start:null,quiet_end:null,timezone:'UTC'};});route('get','/notifications/:id',r=>notifications.get(r,r.params.id));route('post','/notifications/read',r=>notifications.change(r,r.body));route('delete','/notifications/:id',r=>notifications.change(r,{ids:[r.params.id]},true));route('post','/notifications/delete',r=>notifications.change(r,r.body,true));route('put','/notifications/preferences',r=>notifications.preferences(r,r.body));
 route('put','/presence',r=>mutate(pool,r,async(db,actor)=>{requireCapability(actor,'communications.view');const availability=r.body.availability||'available';if(!['available','away','dnd','offline'].includes(availability))fail(400,'invalid_presence');const conversation=r.body.conversation_id?await authorizeConversation(db,actor,r.body.conversation_id):null;await db.query(`INSERT INTO comms_presence(user_id,company_id,availability,status_text,expires_at,conversation_id,typing_until) VALUES($1,$2,$3,$4,now()+interval '75 seconds',$5,CASE WHEN $6 THEN now()+interval '8 seconds' END) ON CONFLICT(user_id) DO UPDATE SET company_id=$2,availability=$3,status_text=$4,expires_at=now()+interval '75 seconds',conversation_id=$5,typing_until=CASE WHEN $6 THEN now()+interval '8 seconds' END,updated_at=now()`,[actor.userId,actor.companyId,availability,text(r.body.status_text||'',140,false),conversation?.id||null,r.body.typing===true]);if(conversation)await publish(db,actor,conversation.id,'presence.changed',actor.userId);return {ok:true};}));
 route('get','/conversations/:id/presence',async r=>{const c=await authorizeConversation(pool,r,r.params.id),people=await messages.participants(pool,c.actor,c.id);return {members:(await pool.query(`SELECT p.user_id,p.availability,p.status_text,p.typing_until,u.display_name,u.photo_url FROM comms_presence p JOIN users u ON u.id=p.user_id WHERE p.company_id=$1 AND p.user_id=ANY($2::uuid[]) AND p.expires_at>now() AND p.availability<>'offline' AND (p.conversation_id=$3 OR p.typing_until IS NULL)`,[c.actor.companyId,people.map(x=>x.id),c.id])).rows};});
 route('get','/events',async r=>{const actor=await loadActor(pool,r),after=Number(r.query.after||0);if(!Number.isSafeInteger(after)||after<0)fail(400,'invalid_cursor');const rows=(await pool.query('SELECT id,conversation_id,recipient_id,event_type,entity_id,payload FROM comms_events WHERE company_id=$1 AND id>$2 ORDER BY id LIMIT 200',[actor.companyId,after])).rows,events=[];for(const row of rows){let allowed=row.recipient_id===actor.userId;if(row.recipient_id&&!allowed)continue;if(!row.recipient_id&&can(actor,'communications.view')){if(row.conversation_id){try{await authorizeConversation(pool,actor,row.conversation_id);allowed=true;}catch(e){if(!e.status)throw e;}}else if(['group.changed','membership.changed'].includes(row.event_type)){allowed=(await pool.query(`SELECT 1 FROM comms_group_members WHERE group_id=$1 AND user_id=$2 AND status IN ('active','invited','left','removed')`,[row.entity_id,actor.userId])).rowCount>0;}}
 if(allowed)events.push({...row,id:Number(row.id),payload:row.event_type==='permission.changed'?{revision:row.payload.revision}:{}});}
 return {events,cursor:rows.length?Number(rows.at(-1).id):after};});
 async function permissionChanged(event){await pool.query(`INSERT INTO comms_events(company_id,recipient_id,event_type,entity_id,payload) SELECT $1,$2,'permission.changed',$3,$4 WHERE NOT EXISTS(SELECT 1 FROM comms_events WHERE event_type='permission.changed' AND entity_id=$3 AND recipient_id=$2)`,[event.companyId,event.userId,event.id,JSON.stringify({revision:event.revision})]);if(app.locals.commsCalls)await app.locals.commsCalls.revokeUser(event.companyId,event.userId);}
 let running=false;const tick=async()=>{if(running)return;running=true;try{await app.locals.permissionGovernance?.drainInvalidations(permissionChanged);await notifications.deliver();await pool.query("DELETE FROM comms_rate_limits WHERE window_at<now()-interval '1 day'");}catch(e){console.error('[comms] background retry',{code:e.code||e.name});}finally{running=false;}};
 const timer=startWorker?setInterval(tick,5000):null;timer?.unref();return {groups,messages,notifications,permissionChanged,stop:()=>clearInterval(timer)};
}
