import {replyOverview,replyParticipantPage} from './reply-participants.js';
import {mentionScopes,resolveMentions} from './mentions.js';
import {randomUUID} from 'node:crypto';
import {authorizeConversation,conversationJoins,conversationAccessSQL,loadActor,can,requireCapability,eligibleMembers,mutate,audit,publish,checkRevision,fail,text,id,ids,pageLimit,cursor,encodeCursor} from './access.js';
import {insertShares,messageCards,validateShares} from './sources.js';
import {authorizeAssets,hydrateMessageAssets} from './assets.js';
export function createConversationService({pool,notify=async()=>{}}){
 async function participants(db,actor,conversation,maximum=200){
  const rows=(await db.query(`SELECT u.id,u.display_name,u.photo_url FROM users u WHERE $1::uuid IS NOT NULL AND u.company_id=$2 AND u.deleted_at IS NULL AND EXISTS(SELECT 1 FROM conversations c ${conversationJoins.replaceAll('$1','u.id')} WHERE c.id=$3 AND ${conversationAccessSQL(actor).replaceAll('$1','u.id')}) ORDER BY u.display_name,u.id LIMIT $4`,[actor.userId,actor.companyId,conversation,maximum])).rows;
  const result=[];for(const user of rows){try{await authorizeConversation(db,{userId:user.id,companyId:actor.companyId},conversation);result.push(user);}catch(error){if(!error.status||error.status>=500)throw error;}if(result.length===maximum)break;}Object.defineProperty(result,'audience_truncated',{value:rows.length>=maximum});return result;
 }

 async function validateMentions(db,actor,conversation,body){const recipients=await participants(db,actor,conversation.id,201);const selection=await resolveMentions(db,actor,conversation,body,recipients,{claim:false});return {mention_scope:selection.mention_scope,mention_user_ids:selection.mention_user_ids};}
 async function list(actor){actor=await loadActor(pool,actor);requireCapability(actor,'communications.view');const rows=(await pool.query(`SELECT c.*,COALESCE(pref.favorite,false) AS favorite,COALESCE(pref.muted,false) AS muted,COALESCE(pref.sort_order,0) AS personal_order,t.group_id,g.name AS group_name,t.name AS thread_name,t.id AS thread_id,t.kind AS thread_kind,latest.id AS latest_message_id,left(latest.body,200) AS latest_body,(SELECT count(*)::int FROM messages m WHERE (m.conversation_id=c.id OR m.channel_id=t.legacy_channel_id) AND m.sender_id<>$1 AND m.deleted_at IS NULL AND m.created_at>=COALESCE(cp.history_from,'-infinity') AND m.created_at>COALESCE(cp.last_read_at,'-infinity')) AS unread_count,(SELECT count(*)::int FROM comms_mentions mm JOIN messages m ON m.id=mm.message_id WHERE mm.user_id=$1 AND m.sender_id<>$1 AND (m.conversation_id=c.id OR m.channel_id=t.legacy_channel_id) AND m.deleted_at IS NULL AND m.created_at>=COALESCE(cp.history_from,'-infinity') AND m.created_at>COALESCE(cp.last_read_at,'-infinity')) AS mention_count FROM conversations c ${conversationJoins} LEFT JOIN LATERAL(SELECT m.id,m.body FROM messages m WHERE (m.conversation_id=c.id OR m.channel_id=t.legacy_channel_id) AND m.deleted_at IS NULL AND m.created_at>=COALESCE(cp.history_from,'-infinity') ORDER BY m.created_at DESC,m.id DESC LIMIT 1) latest ON true LEFT JOIN comms_preferences pref ON pref.user_id=$1 AND pref.subject_type='conversation' AND pref.subject_id=c.id WHERE ${conversationAccessSQL(actor)} ORDER BY COALESCE(pref.favorite,false) DESC,COALESCE(pref.sort_order,0),c.updated_at DESC,c.id DESC LIMIT 100`,[actor.userId,actor.companyId])).rows;
  const regular=rows.filter(r=>!r.thread_id),memberRows=regular.length?(await pool.query(`SELECT cp.conversation_id,u.id,u.display_name,u.photo_url FROM conversation_participants cp JOIN users u ON u.id=cp.user_id WHERE cp.conversation_id=ANY($1::text[]) AND u.company_id=$2 AND u.deleted_at IS NULL AND cp.left_at IS NULL`,[regular.map(r=>r.id),actor.companyId])).rows:[];
  const previewIDs=rows.filter(row=>row.latest_message_id&&!row.latest_body).map(row=>row.latest_message_id),cards=previewIDs.length?await messageCards(pool,actor,previewIDs):new Map(),assets=previewIDs.length?await hydrateMessageAssets(pool,actor,previewIDs):new Map();
  return rows.map(({latest_message_id,...r})=>{if(latest_message_id&&!r.latest_body){const references=[...cards.get(latest_message_id)||[],...assets.get(latest_message_id)||[]];r.latest_body=references.some(item=>item.accessible!==false&&(item.id||item.accessible))?'Shared item':references.some(item=>item.accessible===false)?'No Access':'Attachment unavailable';}return {...r,participants:memberRows.filter(m=>m.conversation_id===r.id).map(({conversation_id,...m})=>m)};});
 }
 async function create(actor,body){return mutate(pool,actor,async(db,actor)=>{
  requireCapability(actor,'communications.send');const key=id(body.client_key),members=await eligibleMembers(db,actor,[actor.userId,...ids(body.member_ids)]);if(members.length<2)fail(400,'members_required');
  await db.query(`SELECT pg_advisory_xact_lock(hashtextextended($1,0))`,['comms-create:'+actor.companyId+':'+key]);
  const prior=(await db.query(`SELECT entity_id FROM comms_mutations WHERE company_id=$1 AND actor_id=$2 AND mutation_key=$3 AND kind='conversation'`,[actor.companyId,actor.userId,key])).rows[0];if(prior)return {id:prior.entity_id};
  let conversation;
  if(members.length===2&&!body.force_new){const pair=members.sort();await db.query(`SELECT pg_advisory_xact_lock(hashtextextended($1,0))`,['comms-dm:'+actor.companyId+':'+pair.join(':')]);conversation=(await db.query(`SELECT c.id FROM conversations c WHERE c.company_id=$1 AND c.scope='dm' AND c.deleted_at IS NULL AND c.archived_at IS NULL AND (SELECT array_agg(cp.user_id ORDER BY cp.user_id) FROM conversation_participants cp WHERE cp.conversation_id=c.id AND cp.left_at IS NULL)=$2::uuid[] LIMIT 1`,[actor.companyId,pair])).rows[0]?.id;}
  if(!conversation){conversation=randomUUID();await db.query(`INSERT INTO conversations(id,company_id,title,is_group,created_by,scope) VALUES($1,$2,$3,$4,$5,$6)`,[conversation,actor.companyId,text(body.title||'Conversation',100),members.length>2,actor.userId,members.length>2?'group_dm':'dm']);for(const member of members)await db.query(`INSERT INTO conversation_participants(id,conversation_id,user_id) VALUES($1,$2,$3)`,[randomUUID(),conversation,member]);}
  await db.query(`INSERT INTO comms_mutations(company_id,actor_id,mutation_key,kind,entity_id) VALUES($1,$2,$3,'conversation',$4)`,[actor.companyId,actor.userId,key,conversation]);await publish(db,actor,conversation,'conversation.created',conversation);return {id:conversation,scope:members.length>2?'group_dm':'dm',title:body.title||'Conversation',participants:await participants(db,actor,conversation),revision:1};
 });}
 async function hydrate(db,actor,rows){if(!rows.length)return [];
  const visible=rows.filter(r=>!r.deleted_at),messageIds=visible.map(r=>r.id);
  const cards=await messageCards(db,actor,messageIds),assets=await hydrateMessageAssets(db,actor,messageIds);
  const reactions=await db.query(`SELECT r.message_id,r.emoji,count(*)::int AS count,array_agg(r.user_id) AS user_ids,bool_or(r.user_id=$2) AS mine,json_agg(json_build_object('id',u.id,'display_name',u.display_name)) AS participants FROM comms_reactions r JOIN users u ON u.id=r.user_id WHERE r.message_id=ANY($1::text[]) GROUP BY r.message_id,r.emoji`,[messageIds,actor.userId]);
  const replies=await replyOverview(db,actor,messageIds);
  const mentions=(await db.query('SELECT message_id,array_agg(user_id ORDER BY user_id) AS user_ids FROM comms_mentions WHERE message_id=ANY($1::text[]) GROUP BY message_id',[messageIds])).rows;
  const personal=await db.query(`SELECT * FROM comms_message_personal WHERE message_id=ANY($1::text[]) AND user_id=$2`,[messageIds,actor.userId]);
  const pins=await db.query(`SELECT message_id FROM comms_pins WHERE message_id=ANY($1::text[])`,[messageIds]);
  return rows.map(({cursor_created_at,...r})=>{if(r.deleted_at)return {...r,body:'',attachments:[],cards:[],reactions:[],reply_count:0,mention_scope:null,mention_user_ids:[],reply_participants:[],reply_participant_count:0,reply_participants_truncated:false};return {...r,attachments:assets.get(r.id)||[],cards:cards.get(r.id)||[],reactions:reactions.rows.filter(x=>x.message_id===r.id),mention_user_ids:mentions.find(x=>x.message_id===r.id)?.user_ids||[],...(replies.get(r.id)||{reply_count:0,reply_participants:[],reply_participant_count:0,reply_participants_truncated:false}),saved:personal.rows.find(x=>x.message_id===r.id)?.saved||false,followed:personal.rows.find(x=>x.message_id===r.id)?.followed||false,pinned:pins.rows.some(x=>x.message_id===r.id),delivery_state:'accepted'};});
 }
 async function history(actor,conversationId,q={},db=pool){const conversation=await authorizeConversation(db,actor,conversationId);actor=conversation.actor;const parameters=[conversationId,conversation.legacy_channel_id,conversation.history_from||'-infinity'],clauses=['(m.conversation_id=$1 OR m.channel_id=$2)','m.created_at >= $3'];
  const add=value=>{parameters.push(value);return '$'+parameters.length;};const before=cursor(q.before);if(before)clauses.push(`(m.created_at,m.id)<(${add(before.at)}::timestamptz,${add(before.id)})`);
  if(q.reply_root_id){await message(db,actor,q.reply_root_id,conversationId);clauses.push(`m.reply_root_id=${add(q.reply_root_id)}`);}else if(!q.search)clauses.push('m.reply_root_id IS NULL');
  if(q.search){clauses.push('m.deleted_at IS NULL');clauses.push(`to_tsvector('simple',m.body) @@ plainto_tsquery('simple',${add(text(q.search,200))})`);}
  if(q.date){if(!Number.isFinite(Date.parse(q.date)))fail(400,'invalid_date');clauses.push(`m.created_at<${add(q.date)}::timestamptz`);}
  const limit=pageLimit(q.limit);const rows=(await db.query(`SELECT m.*,m.created_at::text AS cursor_created_at,u.display_name AS sender_name,u.photo_url AS sender_photo_url FROM messages m JOIN users u ON u.id=m.sender_id WHERE ${clauses.join(' AND ')} ORDER BY m.created_at DESC,m.id DESC LIMIT ${add(limit+1)}`,parameters)).rows;const page=rows.slice(0,limit);return {messages:(await hydrate(db,actor,page)).reverse(),next_cursor:rows.length>limit?encodeCursor(page.at(-1)):null};
 }
 async function message(db,actor,messageId,expectedConversation=null){const row=(await db.query(`SELECT m.*,u.display_name AS sender_name,u.photo_url AS sender_photo_url,COALESCE(m.conversation_id,t.conversation_id) AS canonical_conversation_id FROM messages m JOIN users u ON u.id=m.sender_id LEFT JOIN comms_threads t ON t.legacy_channel_id=m.channel_id WHERE m.id=$1 AND m.company_id=$2`,[id(messageId),actor.companyId])).rows[0];if(!row)fail(404,'message_unavailable');const c=await authorizeConversation(db,actor,row.canonical_conversation_id);if(expectedConversation&&expectedConversation!==c.id)fail(404,'message_unavailable');if(c.history_from&&Date.parse(row.created_at)<Date.parse(c.history_from))fail(404,'message_unavailable');return {...row,conversation:c};}
 async function replyParticipants(actor,messageId,q={}){const root=await message(pool,actor,messageId);if(root.deleted_at||root.reply_root_id)fail(404,'message_unavailable');return replyParticipantPage(pool,root.conversation.actor,root.id,q.after_id);}
 async function sendInTransaction(db,actor,conversationId,body){
  const conversation=await authorizeConversation(db,actor,conversationId,{write:true});actor=conversation.actor;const key=id(body.client_key);await db.query(`SELECT pg_advisory_xact_lock(hashtextextended($1,0))`,['comms-send:'+actor.userId+':'+key]);
  const prior=(await db.query(`SELECT * FROM messages WHERE company_id=$1 AND sender_id=$2 AND client_key=$3`,[actor.companyId,actor.userId,key])).rows[0];if(prior){if(prior.conversation_id!==conversationId)fail(409,'idempotency_conflict');return (await hydrate(db,actor,[prior]))[0];}
  const content=text(body.body||'',20000,false),assets=await authorizeAssets(db,actor,body.asset_ids||[]),cards=body.cards||[];if(assets.length||cards.length)requireCapability(actor,'communications.share');await validateShares(db,actor,cards);if(!content&&!assets.length&&!cards.length)fail(400,'empty_message');
  if(body.reply_root_id){const parent=await message(db,actor,body.reply_root_id,conversationId);if(parent.deleted_at||parent.reply_root_id)fail(400,'invalid_reply_root');}
  const recipients=await participants(db,actor,conversationId,201),selection=await resolveMentions(db,actor,conversation,body,recipients);const mentions=selection.resolved_user_ids;
  const messageId=randomUUID();const row=(await db.query(`INSERT INTO messages(id,company_id,conversation_id,sender_id,body,client_key,reply_root_id,mention_scope) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[messageId,actor.companyId,conversationId,actor.userId,content,key,body.reply_root_id||null,selection.mention_scope])).rows[0];
  for(const [order,file] of assets.entries())await db.query(`INSERT INTO comms_asset_refs(id,message_id,asset_id,company_id,sort_order) VALUES($1,$2,$3,$4,$5)`,[randomUUID(),messageId,file.id,actor.companyId,order]);await insertShares(db,actor,messageId,cards);
  for(const user of mentions)await db.query(`INSERT INTO comms_mentions(message_id,user_id) VALUES($1,$2)`,[messageId,user]);
  await db.query(`UPDATE conversations SET updated_at=now(),revision=revision+1 WHERE id=$1`,[conversationId]);await publish(db,actor,conversationId,'message.created',messageId,{revision:1});
  await notify(db,actor,{key:'message:'+messageId,kind:'comms.message',conversation_id:conversationId,source_refs:cards,title:mentions.length?'Company Comms mention':'New Company Comms message',body:'Open Company Comms to read the conversation.',recipients:recipients.map(x=>x.id).filter(x=>x!==actor.userId),message_id:messageId});
  return (await hydrate(db,actor,[{...row,sender_name:actor.displayName}]))[0];
 }
 async function send(actor,conversationId,body){return mutate(pool,actor,(db,current)=>sendInTransaction(db,current,conversationId,body));}
 async function edit(actor,messageId,body,remove=false){return mutate(pool,actor,async(db,actor)=>{
  await db.query('SELECT id FROM messages WHERE id=$1 FOR UPDATE',[id(messageId)]);const row=await message(db,actor,messageId);checkRevision(row,body.expected_revision);await authorizeConversation(db,actor,row.canonical_conversation_id,{write:true});if(row.deleted_at)fail(409,'message_deleted');
  if(row.sender_id!==actor.userId){if(!remove||!can(actor,'communications.moderate'))fail(403,'message_author_required');text(body.reason,500);}
  await db.query(`INSERT INTO comms_message_versions(message_id,revision,body,actor_id) VALUES($1,$2,$3,$4)`,[messageId,row.revision,row.body,actor.userId]);
  const saved=(await db.query(`UPDATE messages SET body=$2,edited_at=CASE WHEN $3 THEN edited_at ELSE now() END,deleted_at=CASE WHEN $3 THEN now() END,revision=revision+1,updated_at=now() WHERE id=$1 RETURNING *`,[messageId,remove?'':text(body.body,20000),remove])).rows[0];
  if(remove){await db.query('DELETE FROM comms_asset_refs WHERE message_id=$1',[messageId]);await audit(db,actor,'message_deleted','message',messageId,{reason:body.reason||'author_deleted'});}await publish(db,actor,row.canonical_conversation_id,remove?'message.deleted':'message.updated',messageId,{revision:saved.revision});return (await hydrate(db,actor,[saved]))[0];
 });}
 async function reaction(actor,messageId,body){return mutate(pool,actor,async(db,actor)=>{const row=await message(db,actor,messageId);await authorizeConversation(db,actor,row.canonical_conversation_id,{write:true});if(row.deleted_at)fail(404,'message_unavailable');const emoji=text(body.emoji,32);if(body.remove)await db.query('DELETE FROM comms_reactions WHERE message_id=$1 AND user_id=$2 AND emoji=$3',[messageId,actor.userId,emoji]);else await db.query('INSERT INTO comms_reactions(message_id,user_id,emoji) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[messageId,actor.userId,emoji]);await publish(db,actor,row.canonical_conversation_id,'message.reaction',messageId);return {ok:true};});}
 async function read(actor,conversationId,body,unread=false){return mutate(pool,actor,async(db,actor)=>{await authorizeConversation(db,actor,conversationId);const point=body.last_message_id||body.before_message_id;const row=point?await message(db,actor,point,conversationId):null;if(!row&&!unread)fail(400,'visible_message_required');// Keep the database timestamp precision: JS Date truncates microseconds and can leave the just-read message unread.
  await db.query(`INSERT INTO conversation_participants(id,conversation_id,user_id,last_read_at) VALUES($1,$2,$3,COALESCE((SELECT created_at-CASE WHEN $5 THEN interval '1 microsecond' ELSE interval '0 seconds' END FROM messages WHERE id=$4),to_timestamp(0))) ON CONFLICT(conversation_id,user_id) DO UPDATE SET last_read_at=CASE WHEN $5 THEN EXCLUDED.last_read_at ELSE GREATEST(conversation_participants.last_read_at,EXCLUDED.last_read_at) END`,[randomUUID(),conversationId,actor.userId,row?.id||null,unread]);await publish(db,actor,conversationId,'read.changed',actor.userId);return {ok:true};});}
 async function personal(actor,messageId,body){return mutate(pool,actor,async(db,actor)=>{await message(db,actor,messageId);if(body.remind_at&&!Number.isFinite(Date.parse(body.remind_at)))fail(400,'invalid_date');return (await db.query(`INSERT INTO comms_message_personal(message_id,user_id,saved,followed,remind_at) VALUES($1,$2,COALESCE($3,false),COALESCE($4,false),$5) ON CONFLICT(message_id,user_id) DO UPDATE SET saved=COALESCE($3,comms_message_personal.saved),followed=COALESCE($4,comms_message_personal.followed),remind_at=CASE WHEN $6 THEN $5 ELSE comms_message_personal.remind_at END RETURNING *`,[messageId,actor.userId,body.saved??null,body.followed??null,body.remind_at||null,Object.hasOwn(body,'remind_at')])).rows[0];});}
 async function pin(actor,messageId,body){return mutate(pool,actor,async(db,actor)=>{const row=await message(db,actor,messageId);await authorizeConversation(db,actor,row.canonical_conversation_id,{write:true});if(body.pinned)await db.query('INSERT INTO comms_pins(message_id,pinned_by) VALUES($1,$2) ON CONFLICT DO NOTHING',[messageId,actor.userId]);else await db.query('DELETE FROM comms_pins WHERE message_id=$1',[messageId]);await audit(db,actor,'message_pin','message',messageId,{pinned:!!body.pinned});await publish(db,actor,row.canonical_conversation_id,'message.pin',messageId);return {ok:true};});}
 async function saved(actor){actor=await loadActor(pool,actor);requireCapability(actor,'communications.view');const rows=(await pool.query(`SELECT m.*,u.display_name AS sender_name FROM comms_message_personal p JOIN messages m ON m.id=p.message_id JOIN users u ON u.id=m.sender_id JOIN conversations c ON c.id=COALESCE(m.conversation_id,(SELECT lt.conversation_id FROM comms_threads lt WHERE lt.legacy_channel_id=m.channel_id)) ${conversationJoins} WHERE p.user_id=$1 AND p.saved AND m.deleted_at IS NULL AND ${conversationAccessSQL(actor)} ORDER BY m.created_at DESC LIMIT 100`,[actor.userId,actor.companyId])).rows;return hydrate(pool,actor,rows);}
 async function members(actor,conversationId,body){
  const c=await authorizeConversation(pool,actor,conversationId,{write:true});if(c.thread_id)fail(400,'use_group_membership');if(body.member_ids){if(body.history_policy!=='new_conversation')fail(400,'history_boundary_required');const current=await participants(pool,c.actor,conversationId);return create(actor,{client_key:body.client_key,title:body.title||c.title,member_ids:[...new Set([...current.map(x=>x.id),...ids(body.member_ids)])],force_new:true});}
  return mutate(pool,actor,async(db,actor)=>{await db.query('SELECT id FROM conversations WHERE id=$1 FOR UPDATE',[conversationId]);const current=await authorizeConversation(db,actor,conversationId,{write:true});checkRevision(current,body.expected_revision);const targets=ids(body.remove_user_ids||[]);if(current.created_by!==actor.userId&&targets.some(x=>x!==actor.userId))fail(403,'conversation_creator_required');const removed=(await db.query('UPDATE conversation_participants SET left_at=now() WHERE conversation_id=$1 AND user_id=ANY($2::uuid[]) AND left_at IS NULL RETURNING user_id',[conversationId,targets])).rows;for(const member of removed)await db.query(`INSERT INTO comms_events(company_id,recipient_id,event_type,entity_id,payload) VALUES($1,$2,'membership.changed',$3,$4)`,[actor.companyId,member.user_id,conversationId,JSON.stringify({conversation_id:conversationId})]);await db.query('UPDATE conversations SET revision=revision+1 WHERE id=$1',[conversationId]);await audit(db,actor,'conversation_members_removed','conversation',conversationId,{user_ids:targets});await publish(db,actor,conversationId,'membership.changed',conversationId);return {ok:true};});
 }
 async function forward(actor,messageId,body){if(body.confirm_text_disclosure!==true)fail(400,'confirm_destination_required');return mutate(pool,actor,async(db,actor)=>{const row=await message(db,actor,messageId);if(row.deleted_at)fail(404,'message_unavailable');const assets=(await db.query('SELECT asset_id FROM comms_asset_refs WHERE message_id=$1 ORDER BY sort_order,created_at,id',[messageId])).rows;const cards=(await db.query('SELECT source_type,source_id,context_type,context_id FROM comms_cards WHERE message_id=$1 ORDER BY sort_order,id',[messageId])).rows;return sendInTransaction(db,actor,id(body.destination_id),{client_key:body.client_key,body:row.body,asset_ids:assets.map(x=>x.asset_id),cards});});}
 return {list,create,history,send,sendInTransaction,edit,reaction,read,personal,pin,saved,members,forward,message,hydrate,participants,mentionScopes,validateMentions,replyParticipants};
}
