import {randomUUID} from 'node:crypto';
import {authorizeConversation,mutate,loadActor,requireCapability,checkRevision,fail,id,uuid,text,audit,publish} from './access.js';
import {authorizeAssets,storagePredicate} from './assets.js';
import {hydrateSources,validateShares} from './sources.js';
import {publicFile} from '../media-storage/domain.js';
export function createNotes({pool}){
 async function row(db,actor,noteId){const note=(await db.query('SELECT n.*,u.display_name AS editor_name FROM comms_notes n LEFT JOIN users u ON u.id=n.editor_id AND u.company_id=n.company_id AND u.deleted_at IS NULL WHERE n.id=$1 AND n.company_id=$2 AND n.deleted_at IS NULL',[uuid(noteId),actor.companyId])).rows[0];if(!note)fail(404,'note_unavailable');const c=await authorizeConversation(db,actor,note.conversation_id);return {note,actor:c.actor};}
 async function hydrate(db,actor,note){const {asset_ids,source_refs,...safe}=note;if(safe.editor_name===undefined)safe.editor_name=(await db.query('SELECT display_name FROM users WHERE id=$1 AND company_id=$2 AND deleted_at IS NULL',[note.editor_id,actor.companyId])).rows[0]?.display_name||null;const cards=[...(await hydrateSources(db,actor,(source_refs||[]).map((ref,i)=>({...ref,id:String(i)})))).values()];const acl=await storagePredicate(db,actor);const files=asset_ids?.length?(await db.query(`SELECT f.id,f.source_protected,CASE WHEN (${acl}) AND f.cloud_status='active' THEN to_jsonb(f)-'object_key'-'upload_id'-'upload_expires_at'-'cleanup_after' END AS file FROM stored_files f WHERE f.id=ANY($3::uuid[]) AND f.company_id=$2`,[actor.userId,actor.companyId,asset_ids])).rows:[];return {...safe,cards,attachments:(asset_ids||[]).map(asset=>{const row=files.find(x=>x.id===asset);return row?.file?publicFile(row.file,actor):row?.source_protected?{accessible:false,text:'No Access'}:{unavailable:true};})};}
 async function get(input,noteId){const {note,actor}=await row(pool,input,noteId);return hydrate(pool,actor,note);}
 async function list(input,conversationId){const c=await authorizeConversation(pool,input,conversationId);const rows=(await pool.query('SELECT n.*,u.display_name AS editor_name FROM comms_notes n LEFT JOIN users u ON u.id=n.editor_id AND u.company_id=n.company_id AND u.deleted_at IS NULL WHERE n.conversation_id=$1 AND n.deleted_at IS NULL ORDER BY n.updated_at DESC,n.id LIMIT 100',[c.id])).rows;const out=[];for(const note of rows)out.push(await hydrate(pool,c.actor,note));return out;}
 async function save(input,conversationId,noteId,body){return mutate(pool,input,async(db,actor)=>{
  requireCapability(actor,'communications.notes');let old;if(noteId){await db.query('SELECT id FROM comms_notes WHERE id=$1 FOR UPDATE',[uuid(noteId)]);({note:old}=await row(db,actor,noteId));conversationId=old.conversation_id;checkRevision(old,body.expected_revision);}const c=await authorizeConversation(db,actor,conversationId,{write:true});
  const key=old?.client_key||id(body.client_key);if(!old){await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['comms-note:'+actor.userId+':'+key]);const previous=(await db.query('SELECT * FROM comms_notes WHERE company_id=$1 AND creator_id=$2 AND client_key=$3',[actor.companyId,actor.userId,key])).rows[0];if(previous){if(previous.conversation_id!==c.id)fail(409,'idempotency_conflict');return get(actor,previous.id);}}
  const assets=body.asset_ids===undefined?old?.asset_ids||[]:body.asset_ids;await authorizeAssets(db,actor,assets);const sourceRefs=await validateShares(db,actor,body.source_refs===undefined?old?.source_refs||[]:body.source_refs);
  const title=text(body.title??old?.title,150),content=text(body.body??old?.body??'',50000,false),note=old?.id||randomUUID();
  if(old)await db.query('INSERT INTO comms_note_versions(note_id,revision,title,body,asset_ids,source_refs,editor_id,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[old.id,old.revision,old.title,old.body,JSON.stringify(old.asset_ids),JSON.stringify(old.source_refs),old.editor_id,old.updated_at]);
  const saved=(await db.query(`INSERT INTO comms_notes(id,company_id,conversation_id,creator_id,editor_id,client_key,title,body,asset_ids,source_refs) VALUES($1,$2,$3,$4,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO UPDATE SET editor_id=$4,title=$6,body=$7,asset_ids=$8,source_refs=$9,revision=comms_notes.revision+1,updated_at=now() RETURNING *`,[note,actor.companyId,c.id,actor.userId,key,title,content,JSON.stringify(assets),JSON.stringify(sourceRefs)])).rows[0];
  await db.query("UPDATE comms_asset_grants SET revoked_at=now() WHERE source_type='note' AND source_id=$1 AND company_id=$2",[note,actor.companyId]);for(const asset of assets)await db.query(`INSERT INTO comms_asset_grants(asset_id,conversation_id,company_id,granted_by,source_type,source_id) VALUES($1,$2,$3,$4,'note',$5) ON CONFLICT(asset_id,conversation_id,source_type,source_id) DO UPDATE SET revoked_at=NULL,granted_by=$4`,[asset,c.id,actor.companyId,actor.userId,note]);
  await audit(db,actor,old?'note_updated':'note_created','note',note,{revision:saved.revision});await publish(db,actor,c.id,'note.changed',note);return hydrate(db,actor,saved);
 });}
 async function remove(input,noteId,body){return mutate(pool,input,async(db,actor)=>{requireCapability(actor,'communications.notes');await db.query('SELECT id FROM comms_notes WHERE id=$1 FOR UPDATE',[uuid(noteId)]);const {note}=await row(db,actor,noteId);checkRevision(note,body.expected_revision);await authorizeConversation(db,actor,note.conversation_id,{write:true});await db.query('UPDATE comms_notes SET deleted_at=now(),revision=revision+1 WHERE id=$1',[noteId]);await db.query("UPDATE comms_asset_grants SET revoked_at=now() WHERE source_type='note' AND source_id=$1",[noteId]);await audit(db,actor,'note_deleted','note',noteId);await publish(db,actor,note.conversation_id,'note.changed',noteId);return {ok:true};});}
 async function versions(input,noteId){const {note,actor}=await row(pool,input,noteId);const rows=(await pool.query('SELECT v.*,u.display_name AS editor_name FROM comms_note_versions v LEFT JOIN users u ON u.id=v.editor_id AND u.company_id=$2 AND u.deleted_at IS NULL WHERE v.note_id=$1 ORDER BY v.revision DESC LIMIT 100',[noteId,actor.companyId])).rows;const out=[];for(const version of rows)out.push(await hydrate(pool,actor,{...version,id:note.id,conversation_id:note.conversation_id}));return out;}
 return {get,list,save,remove,versions,hydrate};
}
