import {randomUUID} from 'node:crypto';
import {mutate,authorizeConversation,fail,text,id,ids,publish,audit} from './access.js';
export function createPolls({pool,messages}){
 async function get(input,messageId,db=pool){const message=await messages.message(db,input,messageId);if(message.deleted_at)fail(404,'poll_unavailable');const row=(await db.query('SELECT * FROM comms_polls WHERE message_id=$1',[messageId])).rows[0];if(!row)fail(404,'poll_unavailable');const options=(await db.query(`SELECT o.id,o.label,o.sort_order,count(v.user_id)::int AS vote_count,COALESCE(bool_or(v.user_id=$2),false) AS selected FROM comms_poll_options o LEFT JOIN comms_poll_votes v ON v.option_id=o.id WHERE o.poll_id=$1 GROUP BY o.id ORDER BY o.sort_order`,[messageId,input.userId])).rows;return {...row,question:message.body,closed:!!row.closed_at||!!row.closes_at&&new Date(row.closes_at)<=new Date(),options,voter_count:Number((await db.query('SELECT count(DISTINCT user_id) AS n FROM comms_poll_votes WHERE poll_id=$1',[messageId])).rows[0].n)};}
 async function create(input,conversationId,body){return mutate(pool,input,async(db,actor)=>{
  if(!Array.isArray(body.options)||body.options.length<2||body.options.length>12)fail(400,'poll_options_required');const options=body.options.map(x=>text(x,200));if(new Set(options.map(x=>x.toLowerCase())).size!==options.length)fail(400,'duplicate_poll_option');if(body.multiple!==undefined&&typeof body.multiple!=='boolean')fail(400,'invalid_poll_mode');const closes=body.closes_at?new Date(body.closes_at):null;if(closes&&(!Number.isFinite(closes.getTime())||closes<=new Date()))fail(400,'invalid_close_time');
  const key=id(body.client_key);await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['comms-send:'+actor.userId+':'+key]);
  const prior=(await db.query('SELECT m.id,p.message_id FROM messages m LEFT JOIN comms_polls p ON p.message_id=m.id WHERE m.company_id=$1 AND m.sender_id=$2 AND m.client_key=$3',[actor.companyId,actor.userId,key])).rows[0];if(prior&&!prior.message_id)fail(409,'idempotency_conflict','This send identifier already belongs to another message.');
  const message=await messages.sendInTransaction(db,actor,conversationId,{client_key:key,body:text(body.question,1000)});const existing=(await db.query('SELECT message_id FROM comms_polls WHERE message_id=$1',[message.id])).rows[0];if(existing)return get(actor,message.id,db);
  await db.query("UPDATE messages SET message_kind='poll' WHERE id=$1",[message.id]);await db.query('INSERT INTO comms_polls(message_id,company_id,author_id,multiple,closes_at) VALUES($1,$2,$3,$4,$5)',[message.id,actor.companyId,actor.userId,body.multiple===true,closes]);for(const [order,label] of options.entries())await db.query('INSERT INTO comms_poll_options(id,poll_id,label,sort_order) VALUES($1,$2,$3,$4)',[randomUUID(),message.id,label,order]);await publish(db,actor,conversationId,'poll.changed',message.id);return get(actor,message.id,db);
 });}
 async function vote(input,messageId,body){return mutate(pool,input,async(db,actor)=>{await db.query('SELECT message_id FROM comms_polls WHERE message_id=$1 FOR UPDATE',[id(messageId)]);const poll=await get(actor,messageId,db);const message=await messages.message(db,actor,messageId);await authorizeConversation(db,actor,message.canonical_conversation_id,{write:true});if(poll.closed)fail(409,'poll_closed');const choices=ids(body.option_ids,12);if(!poll.multiple&&choices.length>1||choices.some(x=>!poll.options.some(o=>o.id===x)))fail(400,'invalid_poll_vote');await db.query('DELETE FROM comms_poll_votes WHERE poll_id=$1 AND user_id=$2',[messageId,actor.userId]);for(const choice of choices)await db.query('INSERT INTO comms_poll_votes(poll_id,option_id,user_id) VALUES($1,$2,$3)',[messageId,choice,actor.userId]);await publish(db,actor,message.canonical_conversation_id,'poll.changed',messageId);return get(actor,messageId,db);});}
 async function close(input,messageId){return mutate(pool,input,async(db,actor)=>{await db.query('SELECT message_id FROM comms_polls WHERE message_id=$1 FOR UPDATE',[id(messageId)]);const poll=await get(actor,messageId,db);if(poll.author_id!==actor.userId)fail(403,'poll_author_required');const message=await messages.message(db,actor,messageId);await authorizeConversation(db,actor,message.canonical_conversation_id,{write:true});await db.query('UPDATE comms_polls SET closed_at=COALESCE(closed_at,now()),revision=revision+1 WHERE message_id=$1',[messageId]);await publish(db,actor,message.canonical_conversation_id,'poll.changed',messageId);await audit(db,actor,'poll_closed','message',messageId);return get(actor,messageId,db);});}
 return {get,create,vote,close};
}
