import {randomUUID} from 'node:crypto';
import {authorizeConversation,mutate,loadActor,requireCapability,checkRevision,fail,id,uuid,text,audit,publish} from './access.js';
import {authorizeAssets} from './assets.js';
import {hydrateSources,validateShares} from './sources.js';
export function createScheduled({pool,messages}){
 const validDate=value=>{const stamp=new Date(value);if(!Number.isFinite(stamp.getTime())||stamp.getTime()<Date.now()+1000||stamp.getTime()>Date.now()+366*86400000)fail(400,'invalid_send_time');return stamp;};
 const zone=value=>{try{new Intl.DateTimeFormat('en',{timeZone:value}).format();return value;}catch{fail(400,'invalid_timezone');}};
 async function hydrate(db,actor,row){const {payload,...safe}=row;return {...safe,body:payload.body,mention_scope:payload.mention_scope||null,mention_user_ids:payload.mention_user_ids||[],reply_root_id:payload.reply_root_id||null,cards:[...(await hydrateSources(db,actor,(payload.cards||[]).map((r,i)=>({...r,id:String(i)})))).values()],asset_ids:payload.asset_ids||[]};}
 async function list(input,conversationId){const c=await authorizeConversation(pool,input,conversationId);const rows=(await pool.query('SELECT * FROM comms_scheduled_messages WHERE conversation_id=$1 AND sender_id=$2 ORDER BY send_at,id LIMIT 100',[c.id,c.actor.userId])).rows;const out=[];for(const r of rows)out.push(await hydrate(pool,c.actor,r));return out;}
 async function save(input,conversationId,scheduleId,body){return mutate(pool,input,async(db,actor)=>{
  let old;if(scheduleId){old=(await db.query('SELECT * FROM comms_scheduled_messages WHERE id=$1 AND sender_id=$2 AND company_id=$3 FOR UPDATE',[uuid(scheduleId),actor.userId,actor.companyId])).rows[0];if(!old)fail(404,'scheduled_unavailable');checkRevision(old,body.expected_revision);if(old.status!=='scheduled')fail(409,'schedule_not_editable');conversationId=old.conversation_id;}
  const c=await authorizeConversation(db,actor,conversationId,{write:true});const payload={body:text(body.body??old?.payload.body??'',20000,false),asset_ids:body.asset_ids??old?.payload.asset_ids??[],cards:body.cards??old?.payload.cards??[],mention_scope:Object.hasOwn(body,'mention_scope')?body.mention_scope:old?.payload.mention_scope??null,mention_user_ids:body.mention_user_ids??old?.payload.mention_user_ids??[],reply_root_id:Object.hasOwn(body,'reply_root_id')?body.reply_root_id:old?.payload.reply_root_id??null};Object.assign(payload,await messages.validateMentions(db,c.actor,c,{...payload,mention_all:body.mention_all}));if(payload.reply_root_id){const parent=await messages.message(db,c.actor,payload.reply_root_id,c.id);if(parent.deleted_at||parent.reply_root_id)fail(400,'invalid_reply_root');}await authorizeAssets(db,actor,payload.asset_ids);await validateShares(db,actor,payload.cards);if(!payload.body&&!payload.asset_ids.length&&!payload.cards.length)fail(400,'empty_message');
  const when=validDate(body.send_at??old?.send_at),timezone=zone(body.timezone??old?.timezone??'UTC'),key=old?.client_key||id(body.client_key);
  const row=(await db.query(`INSERT INTO comms_scheduled_messages(id,company_id,conversation_id,sender_id,client_key,payload,send_at,timezone) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(company_id,sender_id,client_key) DO UPDATE SET payload=CASE WHEN $9 THEN EXCLUDED.payload ELSE comms_scheduled_messages.payload END,send_at=CASE WHEN $9 THEN EXCLUDED.send_at ELSE comms_scheduled_messages.send_at END,timezone=CASE WHEN $9 THEN EXCLUDED.timezone ELSE comms_scheduled_messages.timezone END,revision=comms_scheduled_messages.revision+CASE WHEN $9 THEN 1 ELSE 0 END,updated_at=now() RETURNING *`,[old?.id||randomUUID(),actor.companyId,c.id,actor.userId,key,JSON.stringify(payload),when,timezone,!!old])).rows[0];if(row.conversation_id!==c.id)fail(409,'idempotency_conflict');await audit(db,actor,old?'scheduled_updated':'scheduled_created','scheduled',row.id);return hydrate(db,actor,row);
 });}
 async function cancel(input,scheduleId,body){return mutate(pool,input,async(db,actor)=>{const row=(await db.query('SELECT * FROM comms_scheduled_messages WHERE id=$1 AND sender_id=$2 AND company_id=$3 FOR UPDATE',[uuid(scheduleId),actor.userId,actor.companyId])).rows[0];if(!row)fail(404,'scheduled_unavailable');checkRevision(row,body.expected_revision);if(row.status==='sent')fail(409,'already_sent');await db.query("UPDATE comms_scheduled_messages SET status='canceled',revision=revision+1,updated_at=now() WHERE id=$1",[scheduleId]);await audit(db,actor,'scheduled_canceled','scheduled',scheduleId);return {ok:true};});}
 async function tick(){const pending=(await pool.query("SELECT id,sender_id,company_id FROM comms_scheduled_messages WHERE status='scheduled' AND send_at<=now() ORDER BY send_at,id LIMIT 20")).rows;for(const p of pending){const db=await pool.connect();try{await db.query('BEGIN');await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['comms-permissions:'+p.sender_id]);const row=(await db.query("SELECT * FROM comms_scheduled_messages WHERE id=$1 AND status='scheduled' AND send_at<=now() FOR UPDATE",[p.id])).rows[0];if(!row){await db.query('COMMIT');continue;}await db.query('SAVEPOINT scheduled_send');try{const actor=await loadActor(db,{userId:p.sender_id,companyId:p.company_id});const sent=await messages.sendInTransaction(db,actor,row.conversation_id,{...row.payload,client_key:'scheduled:'+row.id});await db.query("UPDATE comms_scheduled_messages SET status='sent',message_id=$2,revision=revision+1,updated_at=now() WHERE id=$1",[row.id,sent.id]);await audit(db,actor,'scheduled_sent','scheduled',row.id);}catch(error){await db.query('ROLLBACK TO SAVEPOINT scheduled_send');await db.query("UPDATE comms_scheduled_messages SET status='failed',error_code=$2,revision=revision+1,updated_at=now() WHERE id=$1",[row.id,error.status?error.code:'send_unavailable']);}await db.query('COMMIT');}catch(error){await db.query('ROLLBACK');throw error;}finally{db.release();}}}
 return {list,save,cancel,tick};
}
