import {callReadSQL} from './calls/access.js';
import {loadActor,authorizeConversation,requireCapability,can,conversationJoins,conversationAccessSQL,text,id,uuid,cursor,encodeCursor,pageLimit,fail} from './access.js';
import {storagePredicate} from './assets.js';
import {sourceAccessSQL} from './sources.js';
export function createCommsSearch({pool}){
 async function search(input,q={}){
  const actor=await loadActor(pool,input);requireCapability(actor,'communications.view');if(q.conversation_id)await authorizeConversation(pool,actor,q.conversation_id);const kind=q.type||'all';if(!['all','message','note','file','channel','thread','conversation','call','transcript','source'].includes(kind))fail(400,'invalid_search_type');
  const values=[actor.userId,actor.companyId],add=value=>{values.push(value);return '$'+values.length;};const term=add('%'+text(q.search||'',200,false).replace(/[\\%_]/g,'\\$&')+'%');const conversation=q.conversation_id?add(id(q.conversation_id)):null,author=q.author_id?add(uuid(q.author_id)):null;
  const from=q.from?new Date(q.from):null,to=q.to?new Date(q.to):null;if(from&&!Number.isFinite(from.getTime())||to&&!Number.isFinite(to.getTime()))fail(400,'invalid_date');const start=from?add(from):null,end=to?add(to):null,before=cursor(q.cursor);const beforeAt=before?add(before.at):null,beforeId=before?add(before.id):null;
  const shared=(date,conv,who)=>[conversation?`${conv}=${conversation}`:null,author?`${who}=${author}`:null,start?`${date}>=${start}`:null,end?`${date}<=${end}`:null].filter(Boolean).join(' AND ')||'true';
  const queries=[];const include=type=>(kind==='all'||kind===type)&&(!['true'].includes(q.pinned)&&!['true'].includes(q.mentions_me)&&!['true'].includes(q.has_attachment)&&!['true'].includes(q.followed)&&!['true'].includes(q.has_link)||type==='message');
  if(include('message'))queries.push(`SELECT 'message'::text AS type,m.id,c.id AS conversation_id,COALESCE(c.title,'Conversation') AS title,left(m.body,300) AS snippet,m.created_at,m.created_at::text AS cursor_created_at,jsonb_build_object('message_id',m.id,'reply_root_id',m.reply_root_id,'author_id',m.sender_id) AS data FROM messages m JOIN conversations c ON c.id=m.conversation_id OR c.id=(SELECT lt.conversation_id FROM comms_threads lt WHERE lt.legacy_channel_id=m.channel_id) ${conversationJoins} WHERE ${conversationAccessSQL(actor)} AND m.deleted_at IS NULL AND m.created_at>=COALESCE(cp.history_from,'-infinity') AND m.body ILIKE ${term} AND ${shared('m.created_at','c.id','m.sender_id')} ${q.has_attachment==='true'?'AND EXISTS(SELECT 1 FROM comms_asset_refs ar WHERE ar.message_id=m.id)':''} ${q.pinned==='true'?'AND EXISTS(SELECT 1 FROM comms_pins pin WHERE pin.message_id=m.id)':''} ${q.mentions_me==='true'?'AND EXISTS(SELECT 1 FROM comms_mentions mm WHERE mm.message_id=m.id AND mm.user_id=$1)':''} ${q.followed==='true'?'AND EXISTS(SELECT 1 FROM comms_message_personal followed WHERE followed.message_id=m.id AND followed.user_id=$1 AND followed.followed)':''} ${q.has_link==='true'?"AND m.body ~* '(https?://|www[.])[^[:space:]<>]+'":''}`);
  if(include('note'))queries.push(`SELECT 'note'::text,n.id::text,c.id,n.title,left(n.body,300),n.updated_at,n.updated_at::text,jsonb_build_object('note_id',n.id,'revision',n.revision) FROM comms_notes n JOIN conversations c ON c.id=n.conversation_id ${conversationJoins} WHERE ${conversationAccessSQL(actor)} AND n.deleted_at IS NULL AND (n.title||' '||n.body) ILIKE ${term} AND ${shared('n.updated_at','c.id','n.editor_id')}`);
  if(include('file')){const acl=await storagePredicate(pool,actor);queries.push(`SELECT 'file'::text,f.id::text,NULL::text,f.display_name,f.original_filename,f.created_at,f.created_at::text,jsonb_build_object('asset_id',f.id,'category',f.category) FROM stored_files f WHERE f.company_id=$2 AND f.cloud_status='active' AND (${acl}) AND f.display_name ILIKE ${term} AND ${shared('f.created_at','NULL::text','f.owner_user_id')}`);if(conversation)queries[queries.length-1]=queries.at(-1).replace(`NULL::text=${conversation}`,`(EXISTS(SELECT 1 FROM comms_asset_refs ar JOIN messages fm ON fm.id=ar.message_id WHERE ar.asset_id=f.id AND fm.conversation_id=${conversation} AND fm.deleted_at IS NULL) OR EXISTS(SELECT 1 FROM comms_asset_grants ag WHERE ag.asset_id=f.id AND ag.conversation_id=${conversation} AND ag.revoked_at IS NULL))`);}
  if(include('channel')&&!conversation&&!author)queries.push(`SELECT 'channel'::text,g.id::text,NULL::text,g.name,''::text,g.created_at,g.created_at::text,'{}'::jsonb FROM comms_groups g JOIN comms_group_members gm ON gm.group_id=g.id AND gm.user_id=$1 AND gm.status='active' WHERE g.company_id=$2 AND g.deleted_at IS NULL AND g.suspended_at IS NULL AND g.name ILIKE ${term} ${start?`AND g.created_at>=${start}`:''} ${end?`AND g.created_at<=${end}`:''}`);
  if(include('thread')||include('conversation'))queries.push(`SELECT CASE WHEN t.id IS NULL THEN 'conversation' ELSE 'thread' END,c.id,c.id,COALESCE(t.name,c.title,'Conversation'),''::text,c.created_at,c.created_at::text,jsonb_build_object('group_id',t.group_id,'thread_id',t.id) FROM conversations c ${conversationJoins} WHERE ${conversationAccessSQL(actor)} AND COALESCE(t.name,c.title,'') ILIKE ${term} AND ${shared('c.created_at','c.id','c.created_by')} ${kind==='thread'?'AND t.id IS NOT NULL':kind==='conversation'?'AND t.id IS NULL':''}`);
  if(include('source'))queries.push(`SELECT 'source'::text,card.id::text,c.id,'Shared '||card.source_type,''::text,card.created_at,card.created_at::text,jsonb_build_object('message_id',m.id,'source_type',card.source_type,'source_id',card.source_id,'context_type',card.context_type,'context_id',card.context_id) FROM comms_cards card JOIN messages m ON m.id=card.message_id JOIN conversations c ON c.id=m.conversation_id ${conversationJoins} WHERE ${conversationAccessSQL(actor)} AND m.deleted_at IS NULL AND ${sourceAccessSQL(actor,'card')} AND (card.source_type||' '||m.body) ILIKE ${term} AND ${shared('card.created_at','c.id','m.sender_id')}`);
  if((include('call')||include('transcript'))&&can(actor,'communications.calls')){
   const tables=(await pool.query("SELECT to_regclass('comms_call_sessions') AS calls,to_regclass('comms_processing_jobs') AS processing")).rows[0];
   if(include('call')&&tables.calls)queries.push(`SELECT 'call'::text,cs.id::text,c.id,COALESCE(c.title,'Call'),cs.kind||' '||cs.media||' '||cs.status,cs.created_at,cs.created_at::text,jsonb_build_object('call_id',cs.id,'status',cs.status) FROM comms_call_sessions cs JOIN conversations c ON c.id=cs.conversation_id ${conversationJoins} WHERE ${conversationAccessSQL(actor)} AND ${callReadSQL(actor)} AND (COALESCE(c.title,'')||' '||cs.kind||' '||cs.status) ILIKE ${term} AND ${shared('cs.created_at','c.id','cs.creator_user_id')}`);
   if(include('transcript')&&tables.processing&&can(actor,'communications.transcribe')){const {processingSearchSQL}=await import('./calls/processing.js');if(processingSearchSQL)queries.push(`SELECT 'transcript'::text,j.id::text,c.id,COALESCE(c.title,'Transcript'),left(j.result::text,300),j.created_at,j.created_at::text,jsonb_build_object('recording_id',r.id,'job_id',j.id) FROM comms_processing_jobs j JOIN comms_call_recordings r ON r.id=j.recording_id JOIN comms_call_sessions cs ON cs.id=r.call_id JOIN stored_files f ON f.id=r.asset_id JOIN conversations c ON c.id=cs.conversation_id ${conversationJoins} WHERE ${conversationAccessSQL(actor)} AND (${processingSearchSQL(actor)}) AND j.kind='transcript' AND j.result::text ILIKE ${term} AND ${shared('j.created_at','c.id','j.requested_by')}`);}
  }
  if(!queries.length)return {results:[],next_cursor:null};const limit=pageLimit(q.limit);const result=(await pool.query(`WITH authorized_results(type,id,conversation_id,title,snippet,created_at,cursor_created_at,data) AS (${queries.join(' UNION ALL ')}) SELECT * FROM authorized_results ${before?`WHERE (created_at,type||':'||id)<(${beforeAt}::timestamptz,${beforeId})`:''} ORDER BY created_at DESC,type||':'||id DESC LIMIT ${add(limit+1)}`,values)).rows;const page=result.slice(0,limit);return {results:page.map(({cursor_created_at,...row})=>row),next_cursor:result.length>limit?encodeCursor({...page.at(-1),id:page.at(-1).type+':'+page.at(-1).id}):null};
 }
 return {search};
}
