import {randomUUID} from 'node:crypto';
import {authorizeConversation,loadActor,mutate,requireCapability,eligibleMembers,checkRevision,fail,text,uuid,id,ids,audit,publish} from './access.js';
import {validateShares,hydrateSources} from './sources.js';
import {authorizeAssets,storagePredicate} from './assets.js';
import {publicFile} from '../media-storage/domain.js';
import {createTaskInTransaction} from './tasks.js';
import {takeRateLimit} from './rate-limits.js';
const TRIGGERS=new Set(['form','manual','job.completed','job.started','task.due']);
function normalizeDefinition(raw){
 if(!raw||!TRIGGERS.has(raw.trigger))fail(400,'invalid_workflow_trigger');if(!Array.isArray(raw.fields)||raw.fields.length>12)fail(400,'invalid_form_fields');const seen=new Set();
 const fields=raw.fields.map(f=>{if(!/^[a-z][a-z0-9_]{0,39}$/.test(f.id||'')||seen.has(f.id))fail(400,'invalid_form_field_id');seen.add(f.id);if(!['text','number','boolean','date','choice'].includes(f.type))fail(400,'invalid_form_field_type');const choices=f.type==='choice'&&Array.isArray(f.choices)?f.choices.map(v=>text(v,200)):[];if(f.type==='choice'&&(choices.length<2||choices.length>20))fail(400,'invalid_form_choices');return {id:f.id,label:text(f.label,100),type:f.type,required:f.required===true,choices};});
 const conditions=raw.conditions||[];if(!Array.isArray(conditions)||conditions.length>5||conditions.some(c=>!seen.has(c.field)||!['equals','not_equals'].includes(c.operator)||typeof c.value==='object'))fail(400,'invalid_workflow_conditions');
 if(!Array.isArray(raw.actions)||!raw.actions.length||raw.actions.length>3)fail(400,'invalid_workflow_actions');const actions=raw.actions.map(a=>{if(!['post_message','create_task','remind'].includes(a.type))fail(400,'invalid_workflow_action');const dueField=a.due_field||'due_date';if(a.type==='remind'&&!fields.some(f=>f.id===dueField&&f.type==='date'))fail(400,'reminder_date_field_required');return {type:a.type,template:text(a.template||'',3000,false),due_field:dueField,minutes_before:Math.max(0,Math.min(10080,Number(a.minutes_before)||0))};});
 const approver_ids=ids(raw.approver_ids,20);if(!approver_ids.length)fail(400,'workflow_approver_required');return {trigger:raw.trigger,fields,conditions:conditions.map(c=>({field:c.field,operator:c.operator,value:c.value})),actions,approver_ids};
}
function validateFields(definition,input){if(!input||typeof input!=='object'||Array.isArray(input))fail(400,'invalid_form_values');const out={};for(const field of definition.fields){const value=input[field.id];if(value==null||value===''){if(field.required)fail(400,'required_form_field',field.label+' is required.');continue;}if(field.type==='text')out[field.id]=text(value,3000);else if(field.type==='number'){if(typeof value!=='number'||!Number.isFinite(value)||Math.abs(value)>1e12)fail(400,'invalid_form_number');out[field.id]=value;}else if(field.type==='boolean'){if(typeof value!=='boolean')fail(400,'invalid_form_boolean');out[field.id]=value;}else if(field.type==='choice'){if(!field.choices.includes(value))fail(400,'invalid_form_choice');out[field.id]=value;}else{const date=new Date(value);if(!Number.isFinite(date.getTime()))fail(400,'invalid_form_date');out[field.id]=date.toISOString();}}return out;}
const render=(template,fields)=>template.replace(/\{\{([a-z][a-z0-9_]*)\}\}/g,(_,key)=>String(fields[key]??''));
export function createWorkflows({pool,messages,notifications}){
 async function workflow(db,input,workflowId){const row=(await db.query('SELECT * FROM comms_workflows WHERE id=$1 AND company_id=$2 AND deleted_at IS NULL',[uuid(workflowId),input.companyId])).rows[0];if(!row)fail(404,'workflow_unavailable');const c=await authorizeConversation(db,input,row.conversation_id);return {row,actor:c.actor};}
 async function list(input,conversationId){const c=await authorizeConversation(pool,input,conversationId);return (await pool.query('SELECT * FROM comms_workflows WHERE conversation_id=$1 AND deleted_at IS NULL ORDER BY name,id LIMIT 100',[c.id])).rows;}
 async function save(input,conversationId,workflowId,body){return mutate(pool,input,async(db,actor)=>{requireCapability(actor,'communications.workflows');let old;if(workflowId){await db.query('SELECT id FROM comms_workflows WHERE id=$1 FOR UPDATE',[uuid(workflowId)]);({row:old}=await workflow(db,actor,workflowId));if(old.creator_id!==actor.userId&&!actor.isCompanyOwner)fail(403,'workflow_creator_required');checkRevision(old,body.expected_revision);conversationId=old.conversation_id;}await authorizeConversation(db,actor,conversationId,{write:true});const definition=normalizeDefinition(body.definition??old?.definition);for(const who of await eligibleMembers(db,actor,definition.approver_ids))await authorizeConversation(db,{userId:who,companyId:actor.companyId},conversationId);
  const row=(await db.query(`INSERT INTO comms_workflows(id,company_id,conversation_id,creator_id,name,definition,enabled) VALUES($1,$2,$3,$4,$5,$6,false) ON CONFLICT(id) DO UPDATE SET name=$5,definition=$6,enabled=$7,revision=comms_workflows.revision+1,updated_at=now() RETURNING *`,[old?.id||randomUUID(),actor.companyId,conversationId,actor.userId,text(body.name??old?.name,100),JSON.stringify(definition),old?body.enabled??old.enabled:false])).rows[0];await audit(db,actor,'workflow_saved','workflow',row.id,{enabled:row.enabled,revision:row.revision});return row;
 });}
 async function submit(input,workflowId,body){return mutate(pool,input,async(db,actor)=>{const {row:w}=await workflow(db,actor,workflowId);await authorizeConversation(db,actor,w.conversation_id,{write:true});const fields=validateFields(w.definition,body.fields||{});const refs=await validateShares(db,actor,body.source_refs||[]);const assets=await authorizeAssets(db,actor,body.asset_ids||[]);const assignees=ids(body.assignee_ids||[actor.userId],20);for(const who of await eligibleMembers(db,actor,assignees))await authorizeConversation(db,{userId:who,companyId:actor.companyId},w.conversation_id);
  const matches=w.definition.conditions.every(c=>c.operator==='equals'?fields[c.field]===c.value:fields[c.field]!==c.value);const preview={workflow_id:w.id,name:w.name,matches,approval_required:true,actions:w.definition.actions.map(a=>({...a,preview:render(a.template,fields)}))};if(body.preview===true)return {preview};if(!w.enabled)fail(409,'workflow_disabled');await takeRateLimit(db,{...actor,method:'POST',path:'/workflows/submit'},{bucket:'workflow_submit',limit:20});
  const run=(await db.query(`INSERT INTO comms_workflow_runs(id,workflow_id,company_id,requester_id,client_key,definition_revision,fields,asset_ids,source_refs,assignee_ids,state) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(workflow_id,requester_id,client_key) DO UPDATE SET id=comms_workflow_runs.id RETURNING *`,[randomUUID(),w.id,actor.companyId,actor.userId,id(body.client_key),w.revision,JSON.stringify(fields),JSON.stringify(assets.map(x=>x.id)),JSON.stringify(refs),JSON.stringify(assignees),matches?'pending':'skipped'])).rows[0];
  if(run.state==='pending')for(const asset of run.asset_ids)await db.query("INSERT INTO comms_asset_grants(asset_id,conversation_id,company_id,granted_by,source_type,source_id) VALUES($1,$2,$3,$4,'workflow_run',$5) ON CONFLICT DO NOTHING",[asset,w.conversation_id,actor.companyId,actor.userId,run.id]);
  if(matches)for(const userId of w.definition.approver_ids)await notifications.enqueue(db,{userId,companyId:actor.companyId,kind:'comms.workflow',title:'Workflow approval requested',body:'Review the request in Company Comms.',conversationId:w.conversation_id,eventKey:'workflow:'+run.id});await publish(db,actor,w.conversation_id,'workflow.changed',w.id);return run;
 });}
 async function history(input,workflowId){const {row:w}=await workflow(pool,input,workflowId);return (await pool.query('SELECT id,workflow_id,requester_id,state,revision,error_code,reviewer_id,created_at,reviewed_at FROM comms_workflow_runs WHERE workflow_id=$1 ORDER BY created_at DESC,id LIMIT 100',[w.id])).rows;}
 async function getRun(input,runId,db=pool){const r=(await db.query('SELECT * FROM comms_workflow_runs WHERE id=$1 AND company_id=$2',[uuid(runId),input.companyId])).rows[0];if(!r)fail(404,'workflow_run_unavailable');const {row:w,actor}=await workflow(db,input,r.workflow_id);if(r.requester_id!==actor.userId&&w.creator_id!==actor.userId&&!w.definition.approver_ids.includes(actor.userId))fail(403,'workflow_review_required');const cards=[...(await hydrateSources(db,actor,r.source_refs.map((x,i)=>({...x,id:String(i)})))).values()];const acl=await storagePredicate(db,actor);const files=r.asset_ids.length?(await db.query(`SELECT f.* FROM stored_files f WHERE f.id=ANY($3::uuid[]) AND f.cloud_status='active' AND (${acl})`,[actor.userId,actor.companyId,r.asset_ids])).rows:[];if(cards.some(x=>!x.accessible||x.text==='Unavailable')||files.length!==r.asset_ids.length)return {id:r.id,state:r.state,revision:r.revision,accessible:false,text:'No Access'};return {...r,workflow:w,cards,attachments:files.map(file=>publicFile(file,actor)),accessible:true};}
 async function decide(input,runId,body){return mutate(pool,input,async(db,actor)=>{await db.query('SELECT id FROM comms_workflow_runs WHERE id=$1 FOR UPDATE',[uuid(runId)]);const run=await getRun(actor,runId,db);if(!run.accessible)fail(403,'workflow_source_unavailable');const w=run.workflow;if(!w.definition.approver_ids.includes(actor.userId))fail(403,'workflow_approver_required');if(!['pending','failed'].includes(run.state))return {id:run.id,state:run.state,result:run.result};checkRevision(run,body.expected_revision);if(!['approve','reject'].includes(body.action))fail(400,'invalid_approval_action');if(body.action==='reject'){await db.query("UPDATE comms_workflow_runs SET state='rejected',reviewer_id=$2,reviewed_at=now(),revision=revision+1 WHERE id=$1",[run.id,actor.userId]);await audit(db,actor,'workflow_rejected','workflow_run',run.id);return {id:run.id,state:'rejected'};}
  if(!w.enabled||w.revision!==run.definition_revision)fail(409,'workflow_changed_resubmit');const requester=await loadActor(db,{userId:run.requester_id,companyId:actor.companyId});await authorizeConversation(db,requester,w.conversation_id,{write:true});await authorizeConversation(db,actor,w.conversation_id,{write:true});await validateShares(db,requester,run.source_refs);await authorizeAssets(db,requester,run.asset_ids);const result=[];await db.query('SAVEPOINT workflow_actions');try{for(const [index,action] of w.definition.actions.entries()){
   const content=render(action.template,run.fields)||Object.entries(run.fields).map(([key,value])=>key+': '+value).join('\n');
   if(action.type==='post_message'){const sent=await messages.sendInTransaction(db,requester,w.conversation_id,{client_key:'workflow:'+run.id+':'+index,body:'Workflow · '+w.name+'\n'+content,asset_ids:run.asset_ids,cards:run.source_refs});await db.query("UPDATE messages SET message_kind='workflow' WHERE id=$1",[sent.id]);result.push({type:'message',id:sent.id});}
   else if(action.type==='create_task'){const task=await createTaskInTransaction(db,actor,{conversation_id:w.conversation_id,source_type:'workflow',source_id:run.id,source_refs:run.source_refs,asset_ids:run.asset_ids},{client_key:'workflow:'+run.id+':'+index,title:content.slice(0,300),assignee_ids:run.assignee_ids,due_date:run.fields[action.due_field]||null});result.push({type:'task',id:task.id});}
   else{const due=new Date(run.fields[action.due_field]);if(!Number.isFinite(due.getTime()))fail(400,'reminder_due_required');due.setMinutes(due.getMinutes()-action.minutes_before);for(const recipient of run.assignee_ids){await authorizeConversation(db,{userId:recipient,companyId:actor.companyId},w.conversation_id);const reminder=randomUUID();await db.query('INSERT INTO comms_workflow_reminders(id,run_id,company_id,conversation_id,requester_id,recipient_id,source_refs,due_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[reminder,run.id,actor.companyId,w.conversation_id,requester.userId,recipient,JSON.stringify(run.source_refs),due]);result.push({type:'reminder',id:reminder});}}
  }await db.query("UPDATE comms_workflow_runs SET state='approved',result=$2,reviewer_id=$3,reviewed_at=now(),error_code=NULL,revision=revision+1 WHERE id=$1",[run.id,JSON.stringify(result),actor.userId]);await audit(db,actor,'workflow_approved','workflow_run',run.id,{actions:result.map(x=>x.type)});await db.query("INSERT INTO comms_automation_outbox(id,company_id,actor_id,event_type,subject_type,subject_id,payload) VALUES($1,$2,$3,'comms.workflow.approved','workflow',$4,$5)",[randomUUID(),actor.companyId,actor.userId,w.id,JSON.stringify({workflow_id:w.id,run_id:run.id,automation_event_depth:1})]);await publish(db,actor,w.conversation_id,'workflow.changed',w.id);return {id:run.id,state:'approved',result};
  }catch(error){await db.query('ROLLBACK TO SAVEPOINT workflow_actions');await db.query("UPDATE comms_workflow_runs SET state='failed',error_code=$2,revision=revision+1 WHERE id=$1",[run.id,error.status?error.code:'workflow_action_unavailable']);return {id:run.id,state:'failed',error_code:error.status?error.code:'workflow_action_unavailable'};}
 });}
 async function tick(){const due=(await pool.query('SELECT * FROM comms_workflow_reminders WHERE due_at<=now() AND delivered_at IS NULL AND canceled_at IS NULL ORDER BY due_at LIMIT 20')).rows;for(const row of due){try{await mutate(pool,{userId:row.requester_id,companyId:row.company_id},async(db,actor)=>{await authorizeConversation(db,actor,row.conversation_id);const recipient=await loadActor(db,{userId:row.recipient_id,companyId:row.company_id});await authorizeConversation(db,recipient,row.conversation_id);const cards=await hydrateSources(db,recipient,row.source_refs);if([...cards.values()].some(x=>!x.accessible||x.text==='Unavailable'))fail(403,'source_unavailable');await notifications.enqueue(db,{userId:row.recipient_id,companyId:row.company_id,kind:'comms.workflow_reminder',title:'Workflow reminder',body:'A due-date reminder is ready in Company Comms.',conversationId:row.conversation_id,sourceRefs:row.source_refs,eventKey:'workflow-reminder:'+row.id});await db.query('UPDATE comms_workflow_reminders SET delivered_at=now() WHERE id=$1',[row.id]);});}catch(error){if(!error.status)throw error;await pool.query('UPDATE comms_workflow_reminders SET canceled_at=now() WHERE id=$1',[row.id]);}}
  if(!(await pool.query("SELECT to_regclass('automation_events') AS present")).rows[0].present)return;
  const definitions=(await pool.query("SELECT * FROM comms_workflows WHERE enabled AND deleted_at IS NULL AND definition->>'trigger' IN ('job.completed','job.started','task.due') ORDER BY created_at LIMIT 50")).rows;
  for(const w of definitions){const events=(await pool.query(`SELECT e.* FROM automation_events e WHERE e.company_id=$1 AND e.event_type=$2 AND e.occurred_at>= $3 AND COALESCE(e.payload->>'automation_event_depth','0')='0' AND NOT EXISTS(SELECT 1 FROM comms_workflow_runs r WHERE r.workflow_id=$4 AND r.client_key='event:'||e.id::text) ORDER BY e.occurred_at LIMIT 20`,[w.company_id,w.definition.trigger,w.created_at,w.id])).rows;for(const event of events){try{const creator=await loadActor(pool,{userId:w.creator_id,companyId:w.company_id});requireCapability(creator,'communications.workflows');const type=event.event_type.startsWith('job.')?'job':'task';await submit(creator,w.id,{client_key:'event:'+event.id,fields:event.payload,source_refs:[{source_type:type,source_id:event.subject_id,context_type:type}],assignee_ids:[w.creator_id]});}catch(error){if(!error.status)throw error;await pool.query(`INSERT INTO comms_workflow_runs(id,workflow_id,company_id,requester_id,client_key,definition_revision,fields,state,error_code) VALUES($1,$2,$3,$4,$5,$6,'{}','failed',$7) ON CONFLICT DO NOTHING`,[randomUUID(),w.id,w.company_id,w.creator_id,'event:'+event.id,w.revision,error.code]);}}}
 }
 return {list,save,submit,history,getRun,decide,tick};
}
